import tonicTheme from '@tonic-ui/theme';
import { merge } from '@tonic-ui/utils';
import { resolveTheme } from '@tonic-ui/utils/internal';
import { ensurePlainObject } from 'ensure-type';
import { mapThemeToCSSVariables } from './utils/css-vars';
import { TONIC_THEME } from './constants';

const defaultCSSVariablePrefix = 'tonic';
const defaultCSSVariableRootSelector = ':root';

/**
 * @typedef {Object} CSSVariableConfig
 * @property {string} [prefix='tonic'] - Custom prefix for CSS variables.
 * @property {string} [rootSelector=':root'] - Root selector where CSS variables are defined.
 */

/**
 * @typedef {Object} CreateThemeOptions
 * @property {CSSVariableConfig} [cssVariables={}] - CSS variables configuration. CSS variables are generated by default. To apply them at runtime, pass `useCSSVariables` to `TonicProvider`.
 */

/**
 * Creates a theme object with CSS variable configuration.
 *
 * To enable CSS variables, pass `useCSSVariables` to `TonicProvider`:
 * ```jsx
 * <TonicProvider theme={theme} useCSSVariables>
 *   {children}
 * </TonicProvider>
 * ```
 *
 * @param {CreateThemeOptions & ThemeScales} [options={}] - Theme configuration options.
 * @param {...ThemeScales} args - Additional theme objects to merge.
 * @returns {ThemeScales & { cssVariablePrefix: string, cssVariables: ThemeScales, rootSelector: string }} The created theme object with CSS variables, prefix, and root selector.
 */
const createTheme = (options = {}, ...args) => {
  const {
    cssVariables: cssVariableConfig = {},
    ...rest
  } = options;

  if (typeof cssVariableConfig === 'boolean') {
    console.warn(
      '[Tonic One] The "cssVariables" option in createTheme() no longer accepts a boolean value.\n' +
      '\n' +
      'To enable CSS variables, you should pass "useCSSVariables" to TonicProvider:\n' +
      '  <TonicProvider theme={theme} useCSSVariables>\n' +
      '\n' +
      'To customize CSS variable configuration, pass a configuration object:\n' +
      '  createTheme({ cssVariables: { prefix: "tonic", rootSelector: ":root" } })'
    );
  }

  let theme = merge(
    {
      ...tonicTheme,
    },
    rest,
  );

  // Merge additional arguments into the theme
  theme = args.reduce((acc, arg) => merge(acc, arg), theme);

  // Resolve token references (e.g., {colors.primary} → actual value)
  // Note: Preserves _dark/_light structure for color mode handling
  theme = resolveTheme(theme);

  // Configure the prefix and root selector for CSS variables
  const cssVariablePrefix = cssVariableConfig?.prefix ?? defaultCSSVariablePrefix;
  const rootSelector = cssVariableConfig?.rootSelector ?? defaultCSSVariableRootSelector;

  // Generate a theme object filtered to include only scales supported by CSS variables
  const cssVariableScales = Object.keys(tonicTheme);
  const cssVariableTheme = Object.fromEntries(
    Object.entries(ensurePlainObject(theme)).filter(
      ([key]) => cssVariableScales.includes(key)
    )
  );

  // Create CSS variables with the appropriate prefix (preserve _dark/_light structure for CSS variables)
  // Frozen so the shared map cannot be mutated by consumers — it's a flat name→value map, so a shallow freeze suffices.
  const cssVariables = Object.freeze(mapThemeToCSSVariables(cssVariableTheme, { prefix: cssVariablePrefix }));

  Object.defineProperties(theme, {
    // TONIC_THEME is a non-enumerable property used to identify themes created with `createTheme()`.
    [TONIC_THEME]: { value: true, enumerable: false },

    // All the following properties must be enumerable to remain accessible in `styled-system` and `CSSVariables` after theme propagation.
    cssVariablePrefix: { value: cssVariablePrefix, enumerable: true },
    cssVariables: { value: cssVariables, enumerable: true },
    rootSelector: { value: rootSelector, enumerable: true },
  });

  return theme;
};

export default createTheme;
