// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const AngleDownSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="angle-down-0" d="M12.5 6.5l-4.5 4.5-4.5-4.5 1-1 3.5 3.5 3.5-3.5 1 1z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  AngleDownSVGIcon.displayName = 'AngleDownSVGIcon';
}
export default React.forwardRef(AngleDownSVGIcon);