// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ArrowLeftSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="arrow-left-0" d="M15 9.016h-10.158l3.296 3.283-1.412 1.416-4.716-4.699h-0.009v-0.009l-1-0.996 5.707-5.739 1.418 1.41-3.316 3.335h10.191z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ArrowLeftSVGIcon.displayName = 'ArrowLeftSVGIcon';
}
export default React.forwardRef(ArrowLeftSVGIcon);