// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ArrowLongLeftSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="arrow-long-left-0" d="M16 9h-11.999v3l-4-4 4-4v3h11.999z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ArrowLongLeftSVGIcon.displayName = 'ArrowLongLeftSVGIcon';
}
export default React.forwardRef(ArrowLongLeftSVGIcon);