// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const BoxUploadSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="box-upload-0" d="M14 1h-1v1l1.3 2h-12.6l1.3-2v-1h-1l-2 3v10c0 0.6 0.4 1 1 1h14c0.6 0 1-0.4 1-1v-10l-2-3zM10 10v4h-4v-4h-3l5-5 5 5h-3zM12 3h-8v-1h8v1zM11 1h-6v-1h6v1z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  BoxUploadSVGIcon.displayName = 'BoxUploadSVGIcon';
}
export default React.forwardRef(BoxUploadSVGIcon);