// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const CalendarEmptySVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="calendar-empty-0" d="M16 2v13c-0 0.552-0.448 1-1 1h-14c-0.552-0-1-0.448-1-1v-13c0-0.552 0.448-1 1-1h2v-1h3v1h4v-1h3v1h2c0.552 0 1 0.448 1 1v0zM11 3h1v-2h-1zM4 3h1v-2h-1zM15 4h-14v11h14z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  CalendarEmptySVGIcon.displayName = 'CalendarEmptySVGIcon';
}
export default React.forwardRef(CalendarEmptySVGIcon);