// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const CaretSquareDownSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="caret-square-down-0" d="M4 6h8l-4 5zM14 3h-12v10h12v-10zM14 2c0.552 0 1 0.448 1 1v0 10c0 0.552-0.448 1-1 1v0h-12c-0.552 0-1-0.448-1-1v0-10c0-0.552 0.448-1 1-1v0z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  CaretSquareDownSVGIcon.displayName = 'CaretSquareDownSVGIcon';
}
export default React.forwardRef(CaretSquareDownSVGIcon);