// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ChartAreaSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="chart-area-0" d="M15 13h-13v-4l3-6 4 6 3-4 3 3zM1 14v-13h-1v14h16v-1z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ChartAreaSVGIcon.displayName = 'ChartAreaSVGIcon';
}
export default React.forwardRef(ChartAreaSVGIcon);