// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const CircleOSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="circle-o-0" d="M8 2.5c3.038 0 5.5 2.462 5.5 5.5s-2.462 5.5-5.5 5.5c-3.038 0-5.5-2.462-5.5-5.5v0c0.004-3.036 2.464-5.496 5.5-5.5h0zM8 1c-3.866 0-7 3.134-7 7s3.134 7 7 7c3.866 0 7-3.134 7-7v0c0-3.866-3.134-7-7-7v0z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  CircleOSVGIcon.displayName = 'CircleOSVGIcon';
}
export default React.forwardRef(CircleOSVGIcon);