// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ColumnsSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="columns-0" d="M15 1h-14c-0.6 0-1 0.4-1 1v12c0 0.6 0.4 1 1 1h14c0.6 0 1-0.4 1-1v-12c0-0.6-0.4-1-1-1zM1 14v-11h4v11h-4zM6 14v-11h4v11h-4zM15 14h-4v-11h4v11z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ColumnsSVGIcon.displayName = 'ColumnsSVGIcon';
}
export default React.forwardRef(ColumnsSVGIcon);