// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ContainerSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="container-0" d="M3 2.4l2-0.4 11 2v9l-11 1-2-0.4v-11.2zM6 13h1v-9.3h-1v9.3zM8 12.6h1v-8.6h-1v8.6zM10 12.4h1v-8l-1-0.2v8.2zM12 12.2h1v-7.5l-1-0.2v7.7zM14 12h1v-7l-1-0.2v7.2zM0 3l2-0.4v10.8l-2-0.4v-10z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ContainerSVGIcon.displayName = 'ContainerSVGIcon';
}
export default React.forwardRef(ContainerSVGIcon);