// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const DatabaseSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="database-0" d="M15 6v3c0 1.4-3.1 2.5-7 2.5s-7-1.1-7-2.5v-3c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5zM8 13c-3.9 0-7-1.1-7-2.5v3c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-3c0 1.4-3.1 2.5-7 2.5zM8 0c-3.9 0-7 1.1-7 2.5v2c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-2c0-1.4-3.1-2.5-7-2.5z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  DatabaseSVGIcon.displayName = 'DatabaseSVGIcon';
}
export default React.forwardRef(DatabaseSVGIcon);