// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const FileDownloadOSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="file-download-o-0" d="M2 1h8v4h4v6h1v-7l-4-4h-9c-0.536 0.038-0.962 0.464-1 0.997v14.003c0.038 0.537 0.464 0.962 0.997 1h8.003v-1h-8zM11 1.4l2.6 2.6h-2.6zM16.045 11.997l-4 4-4-4h3v-4h2v4z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  FileDownloadOSVGIcon.displayName = 'FileDownloadOSVGIcon';
}
export default React.forwardRef(FileDownloadOSVGIcon);