// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const InjectSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="inject-0" d="M15.3 3.7l-1-1-1.3 1.3-1-1 1.3-1.3-1-1 0.7-0.7 3 3-0.7 0.7zM9.3 1.7l5 5-0.7 0.7-1-1-6.6 6.6h-1.9l-3.6 2.9c-0.1 0.1-0.3 0.1-0.4 0s-0.1-0.3 0-0.4l2.9-3.6v-1.9l6.6-6.6-1-1 0.7-0.7zM10 4.4l-3.6 3.6h3.2l2-2-1.6-1.6z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  InjectSVGIcon.displayName = 'InjectSVGIcon';
}
export default React.forwardRef(InjectSVGIcon);