// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const LaptopGroupSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="laptop-group-0" d="M16 1v8c0 0.552-0.448 1-1 1v0h-1v-8h-10v-1c0-0.552 0.448-1 1-1v0h10c0.552 0 1 0.448 1 1v0zM1 12v-8c0-0.552 0.448-1 1-1v0h10c0.552 0 1 0.448 1 1v0 8c0 0.552-0.448 1-1 1v0h-10c-0.552 0-1-0.448-1-1v0zM3 11h8v-6h-8zM2 16h10c1.105 0 2-0.895 2-2v0h-14c0 1.105 0.895 2 2 2v0zM14 13c1.105 0 2-0.895 2-2v0h-2z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  LaptopGroupSVGIcon.displayName = 'LaptopGroupSVGIcon';
}
export default React.forwardRef(LaptopGroupSVGIcon);