// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const Light2OSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="light2-o-0" d="M8.8 2.5h-1.6v-2.5h1.5v2.5zM0 9h2.2v-1.5h-2.2v1.5zM13.8 7.5v1.5h2.2v-1.5h-2.2zM2.9 1.8l-1.1 1.1 1.4 1.4 1.1-1.1-1.4-1.4zM13.1 1.8l-1.4 1.4 1.1 1.1 1.4-1.4-1.1-1.1zM12.2 6.5c1.2 2.3 0.4 5.2-1.9 6.4v3.1h-4.5v-3.1c-0.8-0.4-1.5-1.1-1.9-1.9-1.3-2.3-0.5-5.2 1.8-6.4 2.3-1.3 5.2-0.4 6.5 1.9zM9.5 5.8c-1.5-0.8-3.5-0.2-4.4 1.4s-0.3 3.6 1.3 4.4l0.8 0.4v2.5h1.5v-2.5l0.8-0.4c0.6-0.3 1-0.8 1.3-1.3 0.9-1.6 0.3-3.6-1.3-4.5z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  Light2OSVGIcon.displayName = 'Light2OSVGIcon';
}
export default React.forwardRef(Light2OSVGIcon);