// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const MagicSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="magic-0" d="M2 3.5c1.4 0 2.5-1.1 2.5-2.5 0 1.4 1.1 2.5 2.5 2.5-1.4 0-2.5 1.1-2.5 2.5 0-1.4-1.1-2.5-2.5-2.5zM13 1.5c0.8 0 1.5-0.7 1.5-1.5 0 0.8 0.7 1.5 1.5 1.5-0.8 0-1.5 0.7-1.5 1.5 0-0.8-0.7-1.5-1.5-1.5zM15 9.5c-0.8 0-1.5 0.7-1.5 1.5 0-0.8-0.7-1.5-1.5-1.5 0.8 0 1.5-0.7 1.5-1.5 0 0.8 0.7 1.5 1.5 1.5zM11 3l-11 11 2 2 11-11-2-2zM9.5 7.5l-1-1 2.5-2.4 0.9 0.9-2.4 2.5z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  MagicSVGIcon.displayName = 'MagicSVGIcon';
}
export default React.forwardRef(MagicSVGIcon);