// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const MoonSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="moon-0" d="M10.551 1.938c-1.005-0.59-2.213-0.938-3.502-0.938-0.019 0-0.037 0-0.056 0l0.003-0c2.535 1.791 3.835 5.746 2.251 8.481-1.585 2.737-5.487 3.272-8.309 1.979 1.235 2.13 3.504 3.54 6.103 3.54 2.583 0 4.841-1.393 6.063-3.469l0.018-0.033c0.591-1.004 0.94-2.211 0.94-3.5 0-2.579-1.398-4.832-3.477-6.043l-0.033-0.018z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  MoonSVGIcon.displayName = 'MoonSVGIcon';
}
export default React.forwardRef(MoonSVGIcon);