// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ObjectAddSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="object-add-0" d="M2 1h12v2h-12zM2 4h10v2h-10zM2 7h8v2h-8zM2 10h4v3.6l-4 1.4zM11.5 11.9l-1.9-1.9-0.6 0.6 1.9 1.9-1.9 1.9 0.6 0.6 1.9-1.9 1.9 1.9 0.6-0.6-1.9-1.9 1.9-1.9-0.6-0.6z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ObjectAddSVGIcon.displayName = 'ObjectAddSVGIcon';
}
export default React.forwardRef(ObjectAddSVGIcon);