// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const PlanStatusSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="plan-status-0" d="M8 0v8l4.3 4.8c-1.2 1-2.7 1.7-4.3 1.7-3.6 0-6.5-2.9-6.5-6.5 0-3.3 2.4-5.9 5.5-6.4v-1.5c-3.9 0.5-7 3.8-7 7.9 0 4.4 3.6 8 8 8 2.1 0 3.9-0.8 5.3-2.1 1.7-1.4 2.7-3.5 2.7-5.9 0-4.4-3.6-8-8-8z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  PlanStatusSVGIcon.displayName = 'PlanStatusSVGIcon';
}
export default React.forwardRef(PlanStatusSVGIcon);