// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const PlaySVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="play-0" d="M3 2v12l10-6-10-6z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  PlaySVGIcon.displayName = 'PlaySVGIcon';
}
export default React.forwardRef(PlaySVGIcon);