// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const PositiveTrueSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="positive-true-0" d="M11.9 14.2l-1.5-1.4-0.4 0.3 1.9 1.9 4.1-4.9-0.4-0.3zM14 2l-8.1 9.8-3.9-3.8-2 2 6 6 10-12z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  PositiveTrueSVGIcon.displayName = 'PositiveTrueSVGIcon';
}
export default React.forwardRef(PositiveTrueSVGIcon);