// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const RegistrySVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="registry-0" d="M0 3h6v6h-6zM0 16h6v-6h-6zM7 16h6v-6h-6zM15 1h-3v3h3zM13 5l-2 2 2 2 2-2zM11 4l-2-2-2 2 2 2z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  RegistrySVGIcon.displayName = 'RegistrySVGIcon';
}
export default React.forwardRef(RegistrySVGIcon);