// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ReorderSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="reorder-0" d="M10 12v-10h2v10h2l-3 4-3-4h2zM8 4l-3-4-3 4h2v10h2v-10h2z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ReorderSVGIcon.displayName = 'ReorderSVGIcon';
}
export default React.forwardRef(ReorderSVGIcon);