// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ResizeHorizontalSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="resize-horizontal-0" d="M15 9h-6v4h2l-3 3-3-3h2v-4h-6v-2h6v-4h-2l3-3 3 3h-2v4h6z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ResizeHorizontalSVGIcon.displayName = 'ResizeHorizontalSVGIcon';
}
export default React.forwardRef(ResizeHorizontalSVGIcon);