// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const SortUpSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="sort-up-0" d="M10.3 8l-2.3-2.19v6.19h-1v-6.19l-2.3 2.19-0.7-0.667 3.5-3.333 3.5 3.333z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  SortUpSVGIcon.displayName = 'SortUpSVGIcon';
}
export default React.forwardRef(SortUpSVGIcon);