// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const SortDownSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="sort-down-0" d="M11 8.667l-3.5 3.333-3.5-3.333 0.7-0.667 2.3 2.19v-6.19h1v6.19l2.3-2.19z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  SortDownSVGIcon.displayName = 'SortDownSVGIcon';
}
export default React.forwardRef(SortDownSVGIcon);