// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const TaskAddOSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="task-add-o-0" d="M16 11v2h-3v3h-2v-3h-3v-2h3v-3h2v3h3zM2 15h8v1h-8c-0.552 0-1-0.448-1-1v0-13c0-0.552 0.448-1 1-1v0h2v-1h8v1h2c0.552 0 1 0.448 1 1v0 8h-1v-8h-2v1h-8v-1h-2v13zM5 1v1h6v-1h-6z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  TaskAddOSVGIcon.displayName = 'TaskAddOSVGIcon';
}
export default React.forwardRef(TaskAddOSVGIcon);