// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const UserWarningSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="user-warning-0" d="M5 11c0-3 2.2-5.5 5.1-5.9 0.2-0.5 0.4-1 0.4-1.6 0-1.9-1.6-3.5-3.5-3.5s-3.5 1.6-3.5 3.5c0 1.4 0.8 2.6 2 3.2v0.5h-0.1c-1.4 0.4-2.6 1.1-3.6 2.1-1.2 1.2-3.6 4.7 0.4 4.7h3.6c-0.5-0.9-0.8-1.9-0.8-3zM11 6c-2.8 0-5 2.2-5 5s2.2 5 5 5 5-2.2 5-5-2.2-5-5-5zM12 14h-2v-1h2v1zM12 12h-2v-4h2v4z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  UserWarningSVGIcon.displayName = 'UserWarningSVGIcon';
}
export default React.forwardRef(UserWarningSVGIcon);