// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const WarningMinorSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="warning-minor-0" d="M15.7 7.3l-7-7c-0.4-0.4-1-0.4-1.4 0l-7 7c-0.4 0.4-0.4 1 0 1.4l7 7c0.4 0.4 1 0.4 1.4 0l7-7c0.4-0.4 0.4-1 0-1.4zM9 12h-2v-2h2v2zM9 9h-2v-5h2v5z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  WarningMinorSVGIcon.displayName = 'WarningMinorSVGIcon';
}
export default React.forwardRef(WarningMinorSVGIcon);