// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const WifiSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="wifi-0" d="M12.8 8.5l-1.6 1.2c-0.7-1-1.9-1.7-3.2-1.7s-2.5 0.7-3.3 1.7l-1.5-1.2c1.1-1.5 2.8-2.5 4.8-2.5s3.7 1 4.8 2.5zM1.6 7.2c1.4-1.9 3.8-3.2 6.4-3.2s5 1.3 6.4 3.2l1.6-1.2c-1.8-2.4-4.7-4-8-4s-6.2 1.6-8 4l1.6 1.2zM8 14c1.1 0 2-0.9 2-2s-0.9-2-2-2-2 0.9-2 2 0.9 2 2 2z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  WifiSVGIcon.displayName = 'WifiSVGIcon';
}
export default React.forwardRef(WifiSVGIcon);