// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const Window8SVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="window8-0" d="M15 7h-8v-5.8l8-1.2v7zM7 8v5.9l8 1.1v-7h-8zM0 12.9l6 0.8v-5.7h-6v4.9zM0 7h6v-5.7l-6 0.8v4.9z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  Window8SVGIcon.displayName = 'Window8SVGIcon';
}
export default React.forwardRef(Window8SVGIcon);