// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react'
import SVGIcon from '../SVGIcon';
import { getIconStyleProps } from '../utils';

const ZoomInSVGIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon ref={ref} viewBox="0 0 16 16" {...styleProps} {...props}>
      <g><path key="zoom-in-0" d="M11.7 10.3c2.1-2.9 1.5-7-1.4-9.1s-7-1.5-9.1 1.4-1.5 7 1.4 9.1c2.3 1.7 5.4 1.7 7.7 0l4.3 4.3 1.4-1.4-4.3-4.3zM6.5 11.5c-2.8 0-5-2.2-5-5s2.2-5 5-5 5 2.2 5 5c0 2.8-2.2 5-5 5zM7 6h3v1h-3v3h-1v-3h-3v-1h3v-3h1v3z" /></g>
    </SVGIcon>
  )
};

if (process.env.NODE_ENV !== 'production') {
  ZoomInSVGIcon.displayName = 'ZoomInSVGIcon';
}
export default React.forwardRef(ZoomInSVGIcon);