// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M15 9h-6v6h-2v-6h-6v-2h6v-6h2v6h6v2z" />,
  'AddIcon',
);
