// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const AddSquareOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="add-square-o-0" d="M7 9h-3v-2h3v-3h2v3h3v2h-3v3h-2v-3zM15 2v12c0 0.552-0.448 1-1 1v0h-12c-0.552 0-1-0.448-1-1v0-12c0-0.552 0.448-1 1-1v0h12c0.552 0 1 0.448 1 1v0zM14 2h-12v12h12v-12z" /></g>
    </SVGIcon>
  );
});

AddSquareOIcon.displayName = 'AddSquareOIcon';

export default AddSquareOIcon;
