// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const AlignCenterIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="align-center-0" d="M11 5h-6v-2h6zM13 6h-10v2h10zM12 9h-8v2h8zM14 12h-12v2h12z" /></g>
    </SVGIcon>
  );
});

AlignCenterIcon.displayName = 'AlignCenterIcon';

export default AlignCenterIcon;
