// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const AlignLeftIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="align-left-0" d="M11 5h-9v-2h9zM11 9h-9v2h9zM13 6h-11v2h11zM14 12h-12v2h12z" /></g>
    </SVGIcon>
  );
});

AlignLeftIcon.displayName = 'AlignLeftIcon';

export default AlignLeftIcon;
