// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const AngleRightIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="angle-right-0" d="M6.501 12.5l-1-1 3.501-3.506-3.49-3.494 1-1 4.488 4.494z" /></g>
    </SVGIcon>
  );
});

AngleRightIcon.displayName = 'AngleRightIcon';

export default AngleRightIcon;
