// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const AppIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="app-0" d="M7 2v4c0 0.6-0.4 1-1 1h-4c-0.6 0-1-0.4-1-1v-4c0-0.6 0.4-1 1-1h4c0.6 0 1 0.4 1 1zM14 1h-4c-0.6 0-1 0.4-1 1v4c0 0.6 0.4 1 1 1h4c0.6 0 1-0.4 1-1v-4c0-0.6-0.4-1-1-1zM6 9h-4c-0.6 0-1 0.4-1 1v4c0 0.6 0.4 1 1 1h4c0.6 0 1-0.4 1-1v-4c0-0.6-0.4-1-1-1zM14 9h-4c-0.6 0-1 0.4-1 1v4c0 0.6 0.4 1 1 1h4c0.6 0 1-0.4 1-1v-4c0-0.6-0.4-1-1-1z" /></g>
    </SVGIcon>
  );
});

AppIcon.displayName = 'AppIcon';

export default AppIcon;
