// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ArrowDownIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="arrow-down-0" d="M13.708 9.297l-5.705 5.726-5.739-5.707 1.41-1.418 3.326 3.307v-10.205h2v10.189l3.292-3.305z" /></g>
    </SVGIcon>
  );
});

ArrowDownIcon.displayName = 'ArrowDownIcon';

export default ArrowDownIcon;
