// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ArrowLongLeftIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="arrow-long-left-0" d="M16 9h-11.999v3l-4-4 4-4v3h11.999z" /></g>
    </SVGIcon>
  );
});

ArrowLongLeftIcon.displayName = 'ArrowLongLeftIcon';

export default ArrowLongLeftIcon;
