// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ArrowLongRightIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="arrow-long-right-0" d="M0.001 7h11.999v-3l4 4-4 4v-3h-11.999z" /></g>
    </SVGIcon>
  );
});

ArrowLongRightIcon.displayName = 'ArrowLongRightIcon';

export default ArrowLongRightIcon;
