// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ArrowsIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="arrows-0" d="M13 11v-2h-4v4h2l-3 3-3-3h2v-4h-4v2l-3-3 3-3v2h4v-4h-2l3-3 3 3h-2v4h4v-2l3 3z" /></g>
    </SVGIcon>
  );
});

ArrowsIcon.displayName = 'ArrowsIcon';

export default ArrowsIcon;
