// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const AsteriskIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="asterisk-0" d="M8.71 7h2.29v1h-2.29l1.62 1.62-0.71 0.71-1.62-1.62v2.29h-1v-2.29l-1.62 1.62-0.71-0.71 1.62-1.62h-2.29v-1h2.29l-1.62-1.62 0.71-0.71 1.62 1.62v-2.29h1v2.29l1.62-1.62 0.71 0.71-1.62 1.62z" /></g>
    </SVGIcon>
  );
});

AsteriskIcon.displayName = 'AsteriskIcon';

export default AsteriskIcon;
