// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const AsteriskIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="asterisk-0" d="M8.71 7h2.29v1h-2.29l1.62 1.62-0.71 0.71-1.62-1.62v2.29h-1v-2.29l-1.62 1.62-0.71-0.71 1.62-1.62h-2.29v-1h2.29l-1.62-1.62 0.71-0.71 1.62 1.62v-2.29h1v2.29l1.62-1.62 0.71 0.71-1.62 1.62z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  AsteriskIcon.displayName = 'AsteriskIcon';
}
export default React.forwardRef(AsteriskIcon);
