// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const BackupIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="backup-0" d="M15 8c-0.042 3.834-3.16 6.925-7 6.925-2.535 0-4.754-1.347-5.983-3.364l-0.017-0.031 1.73-1c0.888 1.47 2.478 2.438 4.294 2.438 2.761 0 5-2.239 5-5s-2.239-5-5-5c-1.644 0-3.103 0.794-4.014 2.019l-0.009 0.013 2 2h-5v-5l1.57 1.57c1.294-1.581 3.245-2.582 5.43-2.582 3.866 0 7 3.134 7 7 0 0.004 0 0.009-0 0.013v-0.001zM14.76 9.86v0 0 0zM8 5v4h3v-1h-2v-3h-1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  BackupIcon.displayName = 'BackupIcon';
}
export default React.forwardRef(BackupIcon);
