// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const BatteryIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="battery-0" d="M13 11h-11v-6h11zM16 8c0 0 0 0.001 0 0.001 0 0.736-0.398 1.38-0.991 1.726l-0.009 0.005v2.268c0 0.552-0.448 1-1 1v0h-13c-0.552 0-1-0.448-1-1v0-8c0-0.552 0.448-1 1-1v0h13c0.552 0 1 0.448 1 1v0 2.268c0.602 0.352 1 0.995 1 1.732 0 0 0 0.001 0 0.001v-0zM14 4h-13v8h13z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  BatteryIcon.displayName = 'BatteryIcon';
}
export default React.forwardRef(BatteryIcon);
