// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const BlockIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="block-0" d="M8 0c-4.418 0-8 3.582-8 8s3.582 8 8 8c4.418 0 8-3.582 8-8v0c0-4.418-3.582-8-8-8v0zM1.5 8c0-0.002 0-0.004 0-0.006 0-1.528 0.53-2.933 1.416-4.039l-0.010 0.013 9.127 9.127c-1.098 0.876-2.505 1.406-4.037 1.406-3.588 0-6.497-2.909-6.497-6.496 0-0.001 0-0.002 0-0.004v0zM13.094 12.033l-9.127-9.127c1.098-0.876 2.505-1.406 4.037-1.406 3.588 0 6.497 2.909 6.497 6.497 0 1.531-0.53 2.939-1.416 4.050l0.010-0.013z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  BlockIcon.displayName = 'BlockIcon';
}
export default React.forwardRef(BlockIcon);
