// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const BlocklistIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="blocklist-0" d="M15 4h-4v-4l4 4zM10 5h5v10c0 0.5-0.5 1-1 1h-12c-0.5 0-1-0.5-1-1v-14c0-0.5 0.5-1 1-1h8v5zM9 12h-2v2h2v-2zM9 6h-2v5h2v-5z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  BlocklistIcon.displayName = 'BlocklistIcon';
}
export default React.forwardRef(BlocklistIcon);
