// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const BookmarkIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="bookmark-0" d="M13 16l-5-4-5 4v-15c0-0.552 0.448-1 1-1v0h8c0.552 0 1 0.448 1 1v0 15z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  BookmarkIcon.displayName = 'BookmarkIcon';
}
export default React.forwardRef(BookmarkIcon);
