// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const BookmarkIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="bookmark-0" d="M13 16l-5-4-5 4v-15c0-0.552 0.448-1 1-1v0h8c0.552 0 1 0.448 1 1v0 15z" /></g>
    </SVGIcon>
  );
});

BookmarkIcon.displayName = 'BookmarkIcon';

export default BookmarkIcon;
