// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const BoxUploadIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="box-upload-0" d="M14 1h-1v1l1.3 2h-12.6l1.3-2v-1h-1l-2 3v10c0 0.6 0.4 1 1 1h14c0.6 0 1-0.4 1-1v-10l-2-3zM10 10v4h-4v-4h-3l5-5 5 5h-3zM12 3h-8v-1h8v1zM11 1h-6v-1h6v1z" /></g>
    </SVGIcon>
  );
});

BoxUploadIcon.displayName = 'BoxUploadIcon';

export default BoxUploadIcon;
