// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CaretRightOIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="caret-right-o-0" d="M5 13.040v-10.080l6.301 5.040zM6 5.040v5.92l3.699-2.96z" /></g>
    </SVGIcon>
  );
});

CaretRightOIcon.displayName = 'CaretRightOIcon';

export default CaretRightOIcon;
