// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M10 8l-5 4v-8z" />,
  'CaretRightIcon',
);
