// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const CaretSquareDownIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="caret-square-down-0" d="M4 6h8l-4 5zM14 3h-12v10h12v-10zM14 2c0.552 0 1 0.448 1 1v0 10c0 0.552-0.448 1-1 1v0h-12c-0.552 0-1-0.448-1-1v0-10c0-0.552 0.448-1 1-1v0z" /></g>
    </SVGIcon>
  );
});

CaretSquareDownIcon.displayName = 'CaretSquareDownIcon';

export default CaretSquareDownIcon;
