// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M5 8l5-4v8z" />,
  'CaretLeftIcon',
);
