// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M5 13.040v-10.080l6.301 5.040zM6 5.040v5.92l3.699-2.96z" />,
  'CaretRightOIcon',
);
