// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CaretSquareUpIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="caret-square-up-0" d="M14 3v10h-12v-10h12zM14 2h-12c-0.552 0-1 0.448-1 1v0 10c0 0.552 0.448 1 1 1v0h12c0.552 0 1-0.448 1-1v0-10c0-0.552-0.448-1-1-1v0zM8 5l-4 5h8z" /></g>
    </SVGIcon>
  );
});

CaretSquareUpIcon.displayName = 'CaretSquareUpIcon';

export default CaretSquareUpIcon;
