// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ChartTableIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="chart-table-0" d="M15 1h-14c-0.552 0.002-0.998 0.448-1 1v12c0.002 0.552 0.448 0.998 1 1h14c0.552-0.002 0.998-0.448 1-1v-12c-0.002-0.552-0.448-0.998-1-1h-0zM10 3v3h-4v-3zM10 7v3h-4v-3zM1 3h4v3h-4zM1 7h4v3h-4zM1 14v-3h4v3zM6 14v-3h4v3zM15 14h-4v-3h4zM15 10h-4v-3h4zM15 6h-4v-3h4z" /></g>
    </SVGIcon>
  );
});

ChartTableIcon.displayName = 'ChartTableIcon';

export default ChartTableIcon;
