// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ChartAreaIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="chart-area-0" d="M15 13h-13v-4l3-6 4 6 3-4 3 3zM1 14v-13h-1v14h16v-1z" /></g>
    </SVGIcon>
  );
});

ChartAreaIcon.displayName = 'ChartAreaIcon';

export default ChartAreaIcon;
