// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ChartBarIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="chart-bar-0" d="M16 14v1h-16v-14h1v13zM5 9h-2v4h2zM8 5h-2v8h2zM11 7h-2v6h2zM14 3h-2v10h2z" /></g>
    </SVGIcon>
  );
});

ChartBarIcon.displayName = 'ChartBarIcon';

export default ChartBarIcon;
