// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ChartAreastepIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="chart-areastep-0" d="M2 10h3v-2h3v-2h3v-2h4v9h-13zM1 14v-13h-1v14h16v-1z" /></g>
    </SVGIcon>
  );
});

ChartAreastepIcon.displayName = 'ChartAreastepIcon';

export default ChartAreastepIcon;
