// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ChartAreaIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="chart-area-0" d="M15 13h-13v-4l3-6 4 6 3-4 3 3zM1 14v-13h-1v14h16v-1z" /></g>
    </SVGIcon>
  );
});

ChartAreaIcon.displayName = 'ChartAreaIcon';

export default ChartAreaIcon;
