// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M6 15l-6-6 2-2 3.9 3.8 8.1-9.8 2 2-10 12z" />,
  'CheckBoldIcon',
);
