// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ChevronRightIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="chevron-right-0" d="M12 8l-6.607 7-1.393-1.476 5.214-5.524-5.214-5.524 1.393-1.476z" /></g>
    </SVGIcon>
  );
});

ChevronRightIcon.displayName = 'ChevronRightIcon';

export default ChevronRightIcon;
