// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ChevronLeftIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="chevron-left-0" d="M4 8l6.607-7 1.393 1.476-5.214 5.524 5.214 5.524-1.393 1.476z" /></g>
    </SVGIcon>
  );
});

ChevronLeftIcon.displayName = 'ChevronLeftIcon';

export default ChevronLeftIcon;
