// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ChevronUpIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="chevron-up-0" d="M8 4l7 6.607-1.476 1.393-5.524-5.214-5.524 5.214-1.476-1.393z" /></g>
    </SVGIcon>
  );
});

ChevronUpIcon.displayName = 'ChevronUpIcon';

export default ChevronUpIcon;
