// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CircleMergeIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="circle-merge-0" d="M0 10c0-3.314 2.686-6 6-6s6 2.686 6 6c0 3.314-2.686 6-6 6v0c-3.312-0.004-5.996-2.688-6-6v-0zM13.44 10.907c1.556-1.098 2.56-2.888 2.56-4.913 0-3.31-2.684-5.994-5.994-5.994-2.025 0-3.815 1.004-4.9 2.542l-0.013 0.019c0.285-0.039 0.614-0.061 0.948-0.061 4.119 0 7.459 3.339 7.459 7.459 0 0.334-0.022 0.664-0.065 0.986l0.004-0.038z" /></g>
    </SVGIcon>
  );
});

CircleMergeIcon.displayName = 'CircleMergeIcon';

export default CircleMergeIcon;
