// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CircleSplitIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="circle-split-0" d="M8 1c-3.866 0-7 3.134-7 7s3.134 7 7 7c3.866 0 7-3.134 7-7v0c0-3.866-3.134-7-7-7v0zM2.5 8c0.004-3.036 2.464-5.496 5.5-5.5h0v11c-3.036-0.004-5.496-2.464-5.5-5.5v-0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  CircleSplitIcon.displayName = 'CircleSplitIcon';
}
export default React.forwardRef(CircleSplitIcon);
