// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CircleDotIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="circle-dot-0" d="M11 8c0 1.657-1.343 3-3 3s-3-1.343-3-3c0-1.657 1.343-3 3-3v0c1.657 0 3 1.343 3 3v0zM15 8c0 3.866-3.134 7-7 7s-7-3.134-7-7c0-3.866 3.134-7 7-7v0c3.866 0 7 3.134 7 7v0zM13.5 8c0-3.038-2.462-5.5-5.5-5.5s-5.5 2.462-5.5 5.5c0 3.038 2.462 5.5 5.5 5.5v0c3.036-0.004 5.496-2.464 5.5-5.5v-0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  CircleDotIcon.displayName = 'CircleDotIcon';
}
export default React.forwardRef(CircleDotIcon);
