// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CityIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="city-0" d="M9 3v12h7v-12h-7zM12 4h1v1h-1v-1zM12 6h1v1h-1v-1zM12 8h1v1h-1v-1zM12 10h1v1h-1v-1zM10 4h1v1h-1v-1zM10 6h1v1h-1v-1zM10 8h1v1h-1v-1zM10 10h1v1h-1v-1zM14 14h-3v-2h3v2zM15 11h-1v-1h1v1zM15 9h-1v-1h1v1zM15 7h-1v-1h1v1zM15 5h-1v-1h1v1zM0 15h8v-14h-8v14zM6 14h-4v-2h4v2zM1 3h6v1h-6v-1zM1 5h6v1h-6v-1zM1 7h6v1h-6v-1zM1 9h6v1h-6v-1z" /></g>
    </SVGIcon>
  );
});

CityIcon.displayName = 'CityIcon';

export default CityIcon;
