// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ClockAddIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="clock-add-0" d="M13 11h3v2h-3v3h-2v-3h-3v-2h3v-3h2v3zM8 8h-4v1h5v-5h-1v4zM1.5 8c0-3.6 2.9-6.5 6.5-6.5s6.5 2.9 6.5 6.5h1.5c0-4.4-3.6-8-8-8s-8 3.6-8 8 3.6 8 8 8v-1.5c-3.6 0-6.5-2.9-6.5-6.5z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ClockAddIcon.displayName = 'ClockAddIcon';
}
export default React.forwardRef(ClockAddIcon);
