// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CodeIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="code-0" d="M4.301 12.707l-4.301-4.353 4.301-4.354 0.699 0.707-3.603 3.647 3.603 3.646zM16 8.354l-4.301-4.354-0.699 0.707 3.603 3.646-3.603 3.647 0.699 0.707zM10 1.209l-0.979-0.209-3 14 0.979 0.209z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  CodeIcon.displayName = 'CodeIcon';
}
export default React.forwardRef(CodeIcon);
