// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M6.5 12.5l-4.5-4.5 4.5-4.5 1 1-3.5 3.5 3.5 3.5-1 1zM12.5 12.5l-4.5-4.5 4.5-4.5 1 1-3.5 3.5 3.5 3.5-1 1z" />,
  'CollapseLeftIcon',
);
