// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CollapseLeftIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="collapse-left-0" d="M6.5 12.5l-4.5-4.5 4.5-4.5 1 1-3.5 3.5 3.5 3.5-1 1zM12.5 12.5l-4.5-4.5 4.5-4.5 1 1-3.5 3.5 3.5 3.5-1 1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  CollapseLeftIcon.displayName = 'CollapseLeftIcon';
}
export default React.forwardRef(CollapseLeftIcon);
