// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CommentIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="comment-0" d="M8 1c-4.42 0-8 2.69-8 6 0.055 1.63 0.845 3.065 2.048 3.991l0.012 0.009-1.060 3s3.070-1.78 3-1.82v0c1.169 0.518 2.532 0.82 3.966 0.82 0.012 0 0.024-0 0.036-0h-0.002c4.42 0 8-2.69 8-6s-3.58-6-8-6zM4 8c-0.552 0-1-0.448-1-1s0.448-1 1-1c0.552 0 1 0.448 1 1v0c0 0.552-0.448 1-1 1v0zM8 8c-0.552 0-1-0.448-1-1s0.448-1 1-1c0.552 0 1 0.448 1 1v0c0 0.552-0.448 1-1 1v0zM12 8c-0.552 0-1-0.448-1-1s0.448-1 1-1c0.552 0 1 0.448 1 1v0c0 0.552-0.448 1-1 1v0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  CommentIcon.displayName = 'CommentIcon';
}
export default React.forwardRef(CommentIcon);
