// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ConnectErrorIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="connect-error-0" d="M6.3 7.3c-0.8 1-1.3 2.2-1.3 3.6-1 0.2-2 0.1-2 0.1l-2 2-1-1 2-2c0 0-0.2-2.8 1-4l1-1 2.3 2.3zM10.9 5c0.2-1 0.1-2 0.1-2l2-2-1-1-2 2c0 0-2.8-0.2-4 1l-1 1 2.3 2.3c1-0.8 2.2-1.3 3.6-1.3zM16 11c0 2.8-2.2 5-5 5s-5-2.2-5-5 2.2-5 5-5 5 2.2 5 5zM12 11l2-2-1-1-2 2-2-2-1 1 2 2-2 2 1 1 2-2 2 2 1-1-2-2z" /></g>
    </SVGIcon>
  );
});

ConnectErrorIcon.displayName = 'ConnectErrorIcon';

export default ConnectErrorIcon;
