// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ConnectWarningIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="connect-warning-0" d="M6.3 7.3c-0.8 1-1.3 2.2-1.3 3.6-1 0.2-2 0.1-2 0.1l-2 2-1-1 2-2c0 0-0.2-2.8 1-4l1-1 2.3 2.3zM10.9 5c0.2-1 0.1-2 0.1-2l2-2-1-1-2 2c0 0-2.8-0.2-4 1l-1 1 2.3 2.3c1-0.8 2.2-1.3 3.6-1.3zM16 11c0 2.8-2.2 5-5 5s-5-2.2-5-5 2.2-5 5-5 5 2.2 5 5zM12 13h-2v1h2v-1zM12 8h-2v4h2v-4z" /></g>
    </SVGIcon>
  );
});

ConnectWarningIcon.displayName = 'ConnectWarningIcon';

export default ConnectWarningIcon;
