// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ConnectingIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="connecting-0" d="M5.354 3.646c0.090 0.090 0.146 0.215 0.146 0.354s-0.056 0.263-0.146 0.354l-3.646 3.646 3.646 3.646c0.090 0.090 0.146 0.216 0.146 0.354 0 0.276-0.224 0.5-0.5 0.5-0.138 0-0.263-0.056-0.354-0.146l-4-4c-0.090-0.090-0.146-0.215-0.146-0.354s0.056-0.263 0.146-0.354l4-4c0.090-0.091 0.215-0.146 0.354-0.146s0.263 0.056 0.354 0.146v0zM5 9c0.552 0 1-0.448 1-1s-0.448-1-1-1c-0.552 0-1 0.448-1 1v0c0 0.552 0.448 1 1 1v0zM8 9c0.552 0 1-0.448 1-1s-0.448-1-1-1c-0.552 0-1 0.448-1 1v0c0 0.552 0.448 1 1 1v0zM12 8c0 0.552-0.448 1-1 1s-1-0.448-1-1c0-0.552 0.448-1 1-1v0c0.552 0 1 0.448 1 1v0zM11.354 3.646c-0.090-0.091-0.216-0.146-0.354-0.146-0.276 0-0.5 0.224-0.5 0.5 0 0.138 0.056 0.263 0.146 0.354l3.646 3.646-3.646 3.646c-0.090 0.090-0.145 0.215-0.145 0.352 0 0.276 0.224 0.5 0.5 0.5 0.137 0 0.262-0.055 0.352-0.145l4-4c0.090-0.091 0.146-0.215 0.146-0.354s-0.056-0.263-0.146-0.354v0z" /></g>
    </SVGIcon>
  );
});

ConnectingIcon.displayName = 'ConnectingIcon';

export default ConnectingIcon;
