// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const CreditTokenIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="credit-token-0" d="M8 0c-4.418 0-8 3.582-8 8s3.582 8 8 8c4.418 0 8-3.582 8-8v0c-0-4.418-3.582-8-8-8h-0zM8 15c-3.866 0-7-3.134-7-7s3.134-7 7-7c3.866 0 7 3.134 7 7v0c-0 3.866-3.134 7-7 7h-0zM8 1.5c-3.59 0-6.5 2.91-6.5 6.5s2.91 6.5 6.5 6.5c3.59 0 6.5-2.91 6.5-6.5v0c-0.004-3.588-2.912-6.496-6.5-6.5h-0zM12 6v1h-1v-1h-2v5h1v1h-4v-1h1v-5h-2v1h-1v-2h8z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  CreditTokenIcon.displayName = 'CreditTokenIcon';
}
export default React.forwardRef(CreditTokenIcon);
