// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const DatabaseIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="database-0" d="M15 6v3c0 1.4-3.1 2.5-7 2.5s-7-1.1-7-2.5v-3c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5zM8 13c-3.9 0-7-1.1-7-2.5v3c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-3c0 1.4-3.1 2.5-7 2.5zM8 0c-3.9 0-7 1.1-7 2.5v2c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-2c0-1.4-3.1-2.5-7-2.5z" /></g>
    </SVGIcon>
  );
});

DatabaseIcon.displayName = 'DatabaseIcon';

export default DatabaseIcon;
