// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const DesktopUpdateIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="desktop-update-0" d="M2 9v-7h10v3h2v-4c0-0.552-0.448-1-1-1v0h-12c-0.552 0-1 0.448-1 1v0 9c0 0.552 0.448 1 1 1v0h5v0.5l-3.75 1.57c-0.148 0.089-0.245 0.248-0.245 0.43 0 0.274 0.221 0.497 0.495 0.5h4.92c-0.264-0.59-0.418-1.278-0.418-2.002 0-1.13 0.375-2.173 1.008-3.010l-0.009 0.013z" />,<path key="desktop-update-1" d="M14.5 12v0c0 1.381-1.119 2.5-2.5 2.5s-2.5-1.119-2.5-2.5c0-1.381 1.119-2.5 2.5-2.5v0 2.5l3-3-3-3v2c-2.209 0-4 1.791-4 4s1.791 4 4 4c2.209 0 4-1.791 4-4v0 0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  DesktopUpdateIcon.displayName = 'DesktopUpdateIcon';
}
export default React.forwardRef(DesktopUpdateIcon);
