// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const DesktopAddIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="desktop-add-0" d="M16 11v2h-3v3h-2v-3h-3v-2h3v-3h2v3zM2 2h10v5h2v-6c0-0.552-0.448-1-1-1v0h-12c-0.552 0-1 0.448-1 1v0 9c0 0.552 0.448 1 1 1v0h5v0.5l-3.75 1.57c-0.148 0.089-0.245 0.248-0.245 0.43 0 0.274 0.221 0.497 0.495 0.5h4.5v-5h-5z" /></g>
    </SVGIcon>
  );
});

DesktopAddIcon.displayName = 'DesktopAddIcon';

export default DesktopAddIcon;
