// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const DesktopIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="desktop-0" d="M15 0h-14c-0.552 0-1 0.448-1 1v11c0 0.552 0.448 1 1 1h6v0.5l-2.75 1.57c-0.148 0.089-0.245 0.248-0.245 0.43 0 0.274 0.221 0.497 0.495 0.5h7c0.274-0.003 0.495-0.226 0.495-0.5 0-0.181-0.096-0.34-0.241-0.428l-0.002-0.001-0.002-0.001-2.75-1.57v-0.5h6c0.552-0 1-0.448 1-1v-11c-0-0.552-0.448-1-1-1h-0zM2 2h12v9h-12z" /></g>
    </SVGIcon>
  );
});

DesktopIcon.displayName = 'DesktopIcon';

export default DesktopIcon;
