// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const Device2Icon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="device2-0" d="M2 2v7h5v5h-4.5c-0 0-0 0-0 0-0.276 0-0.5-0.224-0.5-0.5 0-0.184 0.1-0.345 0.248-0.432l0.002-0.001 3.75-1.567v-0.5h-5c-0.552 0-1-0.448-1-1v0-9c0-0.552 0.448-1 1-1v0h12c0.552 0 1 0.448 1 1v0 1h-12zM16 4v11c0 0.552-0.448 1-1 1v0h-6c-0.552 0-1-0.448-1-1v0-11c0-0.552 0.448-1 1-1v0h6c0.552 0 1 0.448 1 1v0zM13 14h-2v1h2zM15 5h-6v8h6v-8z" /></g>
    </SVGIcon>
  );
});

Device2Icon.displayName = 'Device2Icon';

export default Device2Icon;
