// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const DeviceIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="device-0" d="M14 3h-12l-2 3v6c0 0.6 0.4 1 1 1h14c0.6 0 1-0.4 1-1v-6l-2-3zM11 11h-1v-3h1v3zM14 11h-2v-3h2v3zM1.7 6l1.3-2h10l1.3 2h-12.6z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  DeviceIcon.displayName = 'DeviceIcon';
}
export default React.forwardRef(DeviceIcon);
