// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const Domain2Icon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="domain2-0" d="M0 14v0c0 0.552 0.448 1 1 1h14c0.552 0 1-0.448 1-1v-12c0-0.552-0.448-1-1-1h-14c-0.552 0-1 0.448-1 1zM1 4h14v10h-14zM14.5 3v0c-0.276 0-0.5-0.224-0.5-0.5v0c0-0.276 0.224-0.5 0.5-0.5s0.5 0.224 0.5 0.5c0 0.276-0.224 0.5-0.5 0.5zM13 2.5c0 0.276-0.224 0.5-0.5 0.5s-0.5-0.224-0.5-0.5c0-0.276 0.224-0.5 0.5-0.5v0c0.276 0 0.5 0.224 0.5 0.5v0zM10.5 3v0c-0.276 0-0.5-0.224-0.5-0.5v0c0-0.276 0.224-0.5 0.5-0.5s0.5 0.224 0.5 0.5c0 0.276-0.224 0.5-0.5 0.5zM3 7h10v-1h-10zM3 9h10v-1h-10zM9 11h-6v-1h6z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  Domain2Icon.displayName = 'Domain2Icon';
}
export default React.forwardRef(Domain2Icon);
