// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const DomainIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="domain-0" d="M15.25 12h-0.25v-5h-6v-2h1.25c0.414-0.002 0.748-0.336 0.75-0.75v-3.5c-0.001-0.414-0.336-0.749-0.75-0.75h-4.5c-0.414 0.001-0.749 0.336-0.75 0.75v3.5c0.002 0.414 0.336 0.748 0.75 0.75h1.25v2h-6v5h-0.25c-0.414 0.002-0.748 0.336-0.75 0.75v2.5c0.002 0.414 0.336 0.748 0.75 0.75h2.5c0.414-0.001 0.749-0.336 0.75-0.75v-2.5c-0.001-0.414-0.336-0.749-0.75-0.75h-0.25v-3h4v3h-0.25c-0.414 0.002-0.748 0.336-0.75 0.75v2.5c0.002 0.414 0.336 0.748 0.75 0.75h2.5c0.414-0.002 0.748-0.336 0.75-0.75v-2.5c-0.002-0.414-0.336-0.748-0.75-0.75h-0.25v-3h4v3h-0.25c-0.414 0.002-0.748 0.336-0.75 0.75v2.5c0.002 0.414 0.336 0.748 0.75 0.75h2.5c0.414-0.002 0.748-0.336 0.75-0.75v-2.5c-0.002-0.414-0.336-0.748-0.75-0.75h-0zM3 15h-2v-2h2zM9 15h-2v-2h2zM15 15h-2v-2h2z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  DomainIcon.displayName = 'DomainIcon';
}
export default React.forwardRef(DomainIcon);
