// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const EdgeIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="edge-0" d="M0 7.1c0.5-3.7 3-7.1 7.6-7.1 2.6 0 5.1 1.4 6.4 3.7 0.7 1.1 1 2.5 1 3.8v1.5h-10.2c0 4.1 6.2 4.2 9.2 2v3.7c-2.5 1.3-5.4 1.6-8.2 0.8-3.2-1.3-4.8-4.9-3.5-8.1 0.6-1.6 1.9-2.9 3.5-3.5-0.6 0.7-1 1.6-1.1 2.6h5.8c0.2-1.7-1-3.2-2.7-3.4-0.2 0-0.4 0-0.6 0-2.9 0.1-5.6 1.6-7.2 4v0 0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  EdgeIcon.displayName = 'EdgeIcon';
}
export default React.forwardRef(EdgeIcon);
