// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const EmailArrowOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="email-arrow-o-0" d="M12 8l4 4-4 4v-3h-4v-2h4v-3zM16 3v7h-1v-4.76l-7 4.76-7-4.76v7.76h6v1h-6c-0.552 0-1-0.448-1-1v0-10c0-0.552 0.448-1 1-1v0h14c0.552 0 1 0.448 1 1v0zM15 4v-1h-14v1l7 4.75z" /></g>
    </SVGIcon>
  );
});

EmailArrowOIcon.displayName = 'EmailArrowOIcon';

export default EmailArrowOIcon;
