// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const EmailArrowOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="email-arrow-o-0" d="M12 8l4 4-4 4v-3h-4v-2h4v-3zM16 3v7h-1v-4.76l-7 4.76-7-4.76v7.76h6v1h-6c-0.552 0-1-0.448-1-1v0-10c0-0.552 0.448-1 1-1v0h14c0.552 0 1 0.448 1 1v0zM15 4v-1h-14v1l7 4.75z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  EmailArrowOIcon.displayName = 'EmailArrowOIcon';
}
export default React.forwardRef(EmailArrowOIcon);
