// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const EmailMessageWarningIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="email-message-warning-0" d="M8 0l-8 6.045v8.955c0 0.552 0.448 1 1 1h14c0.552-0 1-0.448 1-1v-8.955l-8-6.045zM15 7.545l-7 5.455-7-5.455v-0.882l7-5.464 7 5.464v0.882zM7 4h2v4h-2v-4zM7 9h2v2h-2v-2z" /></g>
    </SVGIcon>
  );
});

EmailMessageWarningIcon.displayName = 'EmailMessageWarningIcon';

export default EmailMessageWarningIcon;
