// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ExchangeIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="exchange-0" d="M12 6h-11.999v-2h11.999v-2l4 3-4 3zM3.997 8l-3.996 3 3.996 3v-2h12.003v-2h-12.003z" /></g>
    </SVGIcon>
  );
});

ExchangeIcon.displayName = 'ExchangeIcon';

export default ExchangeIcon;
