// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ExportIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="export-0" d="M9 3h3v-2.5l4 4-4 4v-2.5h-3c-4 0-5 3-5 3v-1c0-2.8 2.2-5 5-5zM14 14h-12v-12h4v-1h-4c-0.5 0-1 0.5-1 1v12c0 0.5 0.5 1 1 1h12c0.5 0 1-0.5 1-1v-5h-1v5z" /></g>
    </SVGIcon>
  );
});

ExportIcon.displayName = 'ExportIcon';

export default ExportIcon;
