// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FileAddOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="file-add-o-0" d="M16 11v2h-3v3h-2v-3h-3v-2h3v-3h2v3h3zM2 15h8v1h-8c-0.5 0-1-0.5-1-1v-14c0-0.5 0.5-1 1-1h9l4 4v6h-1v-5h-4v-4h-8v14zM11 4h2.6l-2.6-2.6v2.6z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  FileAddOIcon.displayName = 'FileAddOIcon';
}
export default React.forwardRef(FileAddOIcon);
