// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const FileZipOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="file-zip-o-0" d="M11 0h-9c-0.5 0-1 0.5-1 1v14c0 0.5 0.5 1 1 1h12c0.5 0 1-0.5 1-1v-11l-4-4zM11 1.4l2.6 2.6h-2.6v-2.6zM14 15h-12v-14h2v1h2v-1h4v4h4v10zM6 3v-1h2v1h-2zM4 3h2v1h-2v-1zM6 5v-1h2v1h-2zM4 5h2v1h-2v-1zM6 7v-1h2v1h-2zM4 7h2v1h-2v-1zM6 9v-1h2v1h-2zM4 10v4h4v-4h-2v-1h-2v1zM7 13h-2v-1h2v1z" /></g>
    </SVGIcon>
  );
});

FileZipOIcon.displayName = 'FileZipOIcon';

export default FileZipOIcon;
