// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const FileSourceOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="file-source-o-0" d="M12 0h-8c-0.5 0-1 0.5-1 1v1h-1c-0.5 0-1 0.5-1 1v12c0 0.5 0.5 1 1 1h10c0.5 0 1-0.5 1-1v-1h1c0.5 0 1-0.5 1-1v-10l-3-3zM12 15h-10v-5h4.1c0.2 0.6 0.8 1 1.4 1 0.8 0 1.5-0.7 1.5-1.5s-0.7-1.5-1.5-1.5c-0.7 0-1.2 0.4-1.4 1h-4.1v-6h7v3h3v9zM10 5v-1.6l1.6 1.6h-1.6zM14 13h-1v-8l-3-3h-6v-1h7.6l2.4 2.4v9.6z" /></g>
    </SVGIcon>
  );
});

FileSourceOIcon.displayName = 'FileSourceOIcon';

export default FileSourceOIcon;
