// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FilePptOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="file-ppt-o-0" d="M11 0h-9c-0.5 0-1 0.5-1 1v14c0 0.5 0.5 1 1 1h12c0.5 0 1-0.5 1-1v-11l-4-4zM11 1.4l2.6 2.6h-2.6v-2.6zM14 15h-12v-14h8v4h4v10zM9 6h-4v1h1v6h-1v1h3v-1h-1v-2h2c1.1 0 2-0.9 2-2v-1c0-1.1-0.9-2-2-2zM10 9c0 0.6-0.4 1-1 1h-2v-3h2c0.6 0 1 0.4 1 1v1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  FilePptOIcon.displayName = 'FilePptOIcon';
}
export default React.forwardRef(FilePptOIcon);
