// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const FileVideoOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="file-video-o-0" d="M11 0h-9c-0.5 0-1 0.5-1 1v14c0 0.5 0.5 1 1 1h12c0.5 0 1-0.5 1-1v-11l-4-4zM11 1.4l2.6 2.6h-2.6v-2.6zM14 15h-12v-14h8v4h4v10zM10 9.2l3-2.2v6l-3-2.3v1.3c0 0.5-0.5 1-1 1h-5c-0.5 0-1-0.5-1-1v-4c0-0.5 0.5-1 1-1h5c0.5 0 1 0.5 1 1v1.2z" /></g>
    </SVGIcon>
  );
});

FileVideoOIcon.displayName = 'FileVideoOIcon';

export default FileVideoOIcon;
