// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FilterIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="filter-0" d="M14 1v1h-13v-1h13zM1 4l5 5v7l3-2v-5l5-5v-1h-13v1z" /></g>
    </SVGIcon>
  );
});

FilterIcon.displayName = 'FilterIcon';

export default FilterIcon;
