// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FilterAddIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="filter-add-0" d="M13.867 1.067v-1.067h-13.867v1.067zM5.333 8.533l-5.333-5.333v-1.067h13.867v1.067l-3.2 3.2h-1.067v1.067l-1.067 1.067v1.067h-2.133v4.267h2.133l-3.2 2.133zM12.8 10.667v-3.2h-2.133v3.2h-3.2v2.133h3.2v3.2h2.133v-3.2h3.2v-2.133z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  FilterAddIcon.displayName = 'FilterAddIcon';
}
export default React.forwardRef(FilterAddIcon);
