// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const FirewallOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="firewall-o-0" d="M0 1v14h16v-14zM1 2h7v3h-7zM11 10h-6v-4h6zM4 6v4h-3v-4zM1 11h6v3h-6zM8 14v-3h7v3zM15 10h-3v-4h3zM9 5v-3h6v3z" /></g>
    </SVGIcon>
  );
});

FirewallOIcon.displayName = 'FirewallOIcon';

export default FirewallOIcon;
