// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FlagIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="flag-0" d="M15 3c0 3.685-2.703 5.984-7 6-2.010-0.015-5-1-6 0v7h-1v-15.5h0.85c0.517-0.122 1.11-0.192 1.72-0.192 1.527 0 2.951 0.44 4.152 1.199l-0.032-0.019s5.060 3.457 7.31 1.512z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  FlagIcon.displayName = 'FlagIcon';
}
export default React.forwardRef(FlagIcon);
