// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FolderAddOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="folder-add-o-0" d="M13 11h3v2h-3v3h-2v-3h-3v-2h3v-3h2v3zM16 4v6h-1v-4h-14v8h9v1h-9c-0.552 0-1-0.448-1-1v0-12c0-0.552 0.448-1 1-1v0h6l1 2h7c0.552 0 1 0.448 1 1v0zM15 4h-7.62l-0.28-0.55-0.72-1.45h-5.38v3h14v-1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  FolderAddOIcon.displayName = 'FolderAddOIcon';
}
export default React.forwardRef(FolderAddOIcon);
