// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FolderOpenIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="folder-open-0" d="M16 8l-2.1 6.43c-0.164 0.339-0.505 0.569-0.9 0.57h-12c-0.552 0-1-0.448-1-1v0-12c0-0.552 0.448-1 1-1v0h4l1 2h7c0.552 0 1 0.448 1 1v0 3h-10.64l-2.36 7h1l2-6h12z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  FolderOpenIcon.displayName = 'FolderOpenIcon';
}
export default React.forwardRef(FolderOpenIcon);
