// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const FolderOpenOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="folder-open-o-0" d="M16 7h-2v-3c0-0.552-0.448-1-1-1v0h-7l-1-2h-4c-0.552 0-1 0.448-1 1v0 12c0 0.552 0.448 1 1 1v0h11.6c0.397-0.003 0.739-0.237 0.897-0.574l0.003-0.006zM1 14v-12h3.37l1 2h7.63v3h-9.75l-2.25 7zM14.58 8l-2 6h-10.48l1.9-6h10.58z" /></g>
    </SVGIcon>
  );
});

FolderOpenOIcon.displayName = 'FolderOpenOIcon';

export default FolderOpenOIcon;
