// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const FullscreenExitIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="fullscreen-exit-0" d="M4.5 3.8l-2.8-2.8-0.7 0.7 2.8 2.8h-2.8v1.5h5v-5h-1.5v2.8zM10 10v5h1.5v-2.8l2.8 2.8 0.7-0.7-2.8-2.8h2.8v-1.5h-5zM1 10v1.5h2.8l-2.8 2.8 0.7 0.7 2.8-2.8v2.8h1.5v-5h-5zM15 1.7l-0.7-0.7-2.8 2.8v-2.8h-1.5v5h5v-1.5h-2.8l2.8-2.8z" /></g>
    </SVGIcon>
  );
});

FullscreenExitIcon.displayName = 'FullscreenExitIcon';

export default FullscreenExitIcon;
