// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const GavelIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="gavel-0" d="M11.4 9.6c-0.4 0.4-1 0.4-1.4 0l-0.8-0.7-6.8 6.8c-0.4 0.4-1 0.4-1.4 0l-0.7-0.7c-0.4-0.4-0.4-1 0-1.4l6.8-6.8-0.7-0.7c-0.4-0.4-0.4-1.1 0-1.5l2.2-2.2c0.4-0.4 1.1-0.4 1.5 0l3.5 3.5c0.4 0.4 0.4 1 0 1.4l-2.2 2.3zM5.7 4.6l2.9-2.9c0.4-0.4 0.4-1 0-1.4s-1-0.4-1.4 0l-2.9 2.9c-0.4 0.4-0.4 1 0 1.4s1 0.4 1.4 0zM15.7 7.4c-0.4-0.4-1-0.4-1.4 0l-2.9 2.9c-0.4 0.4-0.4 1 0 1.4s1 0.4 1.4 0l2.9-2.9c0.4-0.4 0.4-1 0-1.4z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  GavelIcon.displayName = 'GavelIcon';
}
export default React.forwardRef(GavelIcon);
