// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const GoogleIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="google-0" d="M16 8c0 4.4-3.6 8-8 8s-8-3.6-8-8 3.6-8 8-8c1.9 0 3.7 0.7 5.1 1.9l-2.1 2.1c-2.2-1.7-5.3-1.2-7 1s-1.2 5.3 1 7 5.3 1.2 7-1c0.3-0.5 0.6-1 0.8-1.5h-4.8v-2.5h7.9c0.1 0.3 0.1 0.7 0.1 1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  GoogleIcon.displayName = 'GoogleIcon';
}
export default React.forwardRef(GoogleIcon);
