// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const InboxIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="inbox-0" d="M14 3h-12l-2 3v6c0 0.6 0.4 1 1 1h14c0.6 0 1-0.4 1-1v-6l-2-3zM11 6c0 1.7-1.3 3-3 3s-3-1.3-3-3h-3.3l1.3-2h10l1.3 2h-3.3z" /></g>
    </SVGIcon>
  );
});

InboxIcon.displayName = 'InboxIcon';

export default InboxIcon;
