// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const IndentIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="indent-0" d="M14 5h-12v-2h12zM14 12h-12v2h12zM14 6h-7v2h7zM14 9h-7v2h7zM2 6v5l3-2.5z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  IndentIcon.displayName = 'IndentIcon';
}
export default React.forwardRef(IndentIcon);
