// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const IndentIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="indent-0" d="M14 5h-12v-2h12zM14 12h-12v2h12zM14 6h-7v2h7zM14 9h-7v2h7zM2 6v5l3-2.5z" /></g>
    </SVGIcon>
  );
});

IndentIcon.displayName = 'IndentIcon';

export default IndentIcon;
