// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const Indicator4Icon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="indicator-4-0" d="M8 11.4c-1.88 0-3.4-1.52-3.4-3.4s1.52-3.4 3.4-3.4c1.88 0 3.4 1.52 3.4 3.4s-1.52 3.4-3.4 3.4zM8 13c2.76 0 5-2.24 5-5s-2.24-5-5-5-5 2.24-5 5 2.24 5 5 5z" /></g>
    </SVGIcon>
  );
});

Indicator4Icon.displayName = 'Indicator4Icon';

export default Indicator4Icon;
