// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const IpIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="ip-0" d="M3 4h1.5v8h-1.5zM7 4h6v5h-4.5v3h-1.5zM8.5 7.5h3v-2h-3zM16 4v8c0 0 0 0 0 0 0 1.657-1.343 3-3 3-0 0-0 0-0 0h-10c-1.657 0-3-1.343-3-3v0-8c0-1.657 1.343-3 3-3v0h10c1.657 0 3 1.343 3 3v0zM15 4c0-1.105-0.895-2-2-2v0h-10c-1.105 0-2 0.895-2 2v0 8c0 1.105 0.895 2 2 2v0h10c1.105 0 2-0.895 2-2v0z" /></g>
    </SVGIcon>
  );
});

IpIcon.displayName = 'IpIcon';

export default IpIcon;
