// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ItalicIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="italic-0" d="M6.649 2h4.351v0.856l-1.016 0.070-0.248 0.253-1.559 9.624 0.188 0.245 1.001 0.079v0.873h-4.366v-0.873l1.016-0.097 0.234-0.262 1.559-9.59-0.158-0.253-1.001-0.070z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ItalicIcon.displayName = 'ItalicIcon';
}
export default React.forwardRef(ItalicIcon);
