// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const KeyOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="key-o-0" d="M14 1c0.552 0.001 0.999 0.448 1 1v5c-0.001 0.552-0.448 0.999-1 1h-4.414l-7 7h-1.586v-1.586l1-1v-1.414h2v-2h1.414l2.586-2.586v-4.414c0.001-0.552 0.448-0.999 1-1h5zM14 0h-5c-1.105 0-2 0.895-2 2v0 4l-2 2h-2v2h-2v2l-1 1v3h3l7-7h4c1.105 0 2-0.895 2-2v0-5c0-1.105-0.895-2-2-2v0zM12.5 3c0.276 0 0.5 0.224 0.5 0.5s-0.224 0.5-0.5 0.5c-0.276 0-0.5-0.224-0.5-0.5v0c0-0.276 0.224-0.5 0.5-0.5h0zM12.5 2c-0.828 0-1.5 0.672-1.5 1.5s0.672 1.5 1.5 1.5c0.828 0 1.5-0.672 1.5-1.5v0c0-0.828-0.672-1.5-1.5-1.5v0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  KeyOIcon.displayName = 'KeyOIcon';
}
export default React.forwardRef(KeyOIcon);
