// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const LaptopIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="laptop-0" d="M2 12h12c0.552 0 1-0.448 1-1v0-9c0-0.552-0.448-1-1-1v0h-12c-0.552 0-1 0.448-1 1v0 9c0 0.552 0.448 1 1 1v0zM3 3h10v7h-10zM16 13c0 1.105-0.895 2-2 2v0h-12c-1.105 0-2-0.895-2-2v0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  LaptopIcon.displayName = 'LaptopIcon';
}
export default React.forwardRef(LaptopIcon);
