// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const LaptopIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="laptop-0" d="M2 12h12c0.552 0 1-0.448 1-1v0-9c0-0.552-0.448-1-1-1v0h-12c-0.552 0-1 0.448-1 1v0 9c0 0.552 0.448 1 1 1v0zM3 3h10v7h-10zM16 13c0 1.105-0.895 2-2 2v0h-12c-1.105 0-2-0.895-2-2v0z" /></g>
    </SVGIcon>
  );
});

LaptopIcon.displayName = 'LaptopIcon';

export default LaptopIcon;
