// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const LinkIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="link-0" d="M13.9 7.5l-1.5 1.5h-2.1l2.6-2.6c0.9-0.9 0.9-2.3 0-3.2s-2.3-0.9-3.2 0v0l-2.7 2.6v-2.2l1.5-1.5c1.5-1.5 3.9-1.5 5.4 0s1.5 3.9 0 5.4v0zM6.4 12.8c-0.9 0.9-2.3 0.9-3.2 0s-0.9-2.3 0-3.2l2.6-2.6h-2.2l-1.5 1.5c-1.5 1.5-1.5 3.9 0 5.4s3.9 1.5 5.3 0l1.6-1.5v-2.1l-2.6 2.5zM5.1 12l6.9-6.9-1.1-1.1-6.9 6.9 1.1 1.1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  LinkIcon.displayName = 'LinkIcon';
}
export default React.forwardRef(LinkIcon);
