// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ListUlIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="list-ul-0" d="M14 4h-9v-2h9zM4 3v0c0-0.552-0.448-1-1-1v0 0c-0.552 0-1 0.448-1 1v0 0c0 0.552 0.448 1 1 1v0 0c0.552 0 1-0.448 1-1v0zM4 8v0c0-0.552-0.448-1-1-1v0 0c-0.552 0-1 0.448-1 1v0 0c0 0.552 0.448 1 1 1v0 0c0.552 0 1-0.448 1-1v0zM4 13v0c0-0.552-0.448-1-1-1v0 0c-0.552 0-1 0.448-1 1v0 0c0 0.552 0.448 1 1 1v0 0c0.552 0 1-0.448 1-1v0zM14 7h-9v2h9zM14 12h-9v2h9z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ListUlIcon.displayName = 'ListUlIcon';
}
export default React.forwardRef(ListUlIcon);
