// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const MapIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="map-0" d="M11 3l-6-2-5 2v12l5-2 6 2 5-2v-12l-5 2zM10.7 8.4l-2.7 4.6-2.7-4.6c-0.2-0.4-0.3-0.9-0.3-1.4 0-1.7 1.3-3 3-3s3 1.3 3 3c0 0.5-0.1 1-0.3 1.4zM8 5.5c0.8 0 1.5 0.7 1.5 1.5s-0.7 1.5-1.5 1.5-1.5-0.7-1.5-1.5 0.7-1.5 1.5-1.5z" /></g>
    </SVGIcon>
  );
});

MapIcon.displayName = 'MapIcon';

export default MapIcon;
