// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MenuIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="menu-0" d="M14 3v2h-12v-2zM2 9h12v-2h-12zM2 13h12v-2h-12z" /></g>
    </SVGIcon>
  );
});

MenuIcon.displayName = 'MenuIcon';

export default MenuIcon;
