// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MenuIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="menu-0" d="M14 3v2h-12v-2zM2 9h12v-2h-12zM2 13h12v-2h-12z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  MenuIcon.displayName = 'MenuIcon';
}
export default React.forwardRef(MenuIcon);
