// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const MigrateSuccessIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="migrate-success-0" d="M4 12v-11.999h-2v11.999h-2l3 4 2.316-3.088c-0.089-0.254-0.167-0.561-0.221-0.876l-0.005-0.035zM7 6.537c0.562-0.506 1.227-0.91 1.958-1.175l0.042-0.013v-1.352h2l-3-3.996-3 3.996h2zM11 6c-2.761 0-5 2.239-5 5s2.239 5 5 5c2.761 0 5-2.239 5-5v0c0-0.008 0-0.018 0-0.028 0-2.746-2.226-4.972-4.972-4.972-0.010 0-0.020 0-0.029 0h0.002zM10 14l-2.54-2.48 1.070-1 1.47 1.48 3.46-3.5 1.070 1.050z" /></g>
    </SVGIcon>
  );
});

MigrateSuccessIcon.displayName = 'MigrateSuccessIcon';

export default MigrateSuccessIcon;
