// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MinusIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="minus-0" d="M1 9v-2h14v2h-14z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  MinusIcon.displayName = 'MinusIcon';
}
export default React.forwardRef(MinusIcon);
