// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MinusSquareOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="minus-square-o-0" d="M12 9h-8v-2h8v2zM15 2v12c0 0.552-0.448 1-1 1v0h-12c-0.552 0-1-0.448-1-1v0-12c0-0.552 0.448-1 1-1v0h12c0.552 0 1 0.448 1 1v0zM14 2h-12v12h12v-12z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  MinusSquareOIcon.displayName = 'MinusSquareOIcon';
}
export default React.forwardRef(MinusSquareOIcon);
