// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const MobileIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="mobile-0" d="M12 0h-8c-0.552 0-1 0.448-1 1v0 14c0 0.552 0.448 1 1 1v0h8c0.552 0 1-0.448 1-1v0-14c0-0.552-0.448-1-1-1v0zM9 15h-2v-1h2zM12 13h-8v-11h8z" /></g>
    </SVGIcon>
  );
});

MobileIcon.displayName = 'MobileIcon';

export default MobileIcon;
