// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MobileGroupIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="mobile-group-0" d="M9 3h-6c-0.552 0-1 0.448-1 1v0 11c0 0.552 0.448 1 1 1v0h6c0.552 0 1-0.448 1-1v0-11c0-0.552-0.448-1-1-1v0zM7 15h-2v-1h2zM9 6v7h-6v-8h6zM14 1v11c0 0.552-0.448 1-1 1v0h-2v-3h2v-8h-7v-1c0-0.552 0.448-1 1-1v0h6c0.552 0 1 0.448 1 1v0z" /></g>
    </SVGIcon>
  );
});

MobileGroupIcon.displayName = 'MobileGroupIcon';

export default MobileGroupIcon;
