// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MonitoringIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="monitoring-0" d="M15 1h-14c-0.552 0-1 0.448-1 1v0 12c0 0.552 0.448 1 1 1v0h14c0.552 0 1-0.448 1-1v0-12c0-0.552-0.448-1-1-1v0zM14 13h-12v-10h12v10zM5 9h-2v-1h1.48l2-3 3 4.22 1.52-2.22h2v1h-1.46l-2 3-3-4.21z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  MonitoringIcon.displayName = 'MonitoringIcon';
}
export default React.forwardRef(MonitoringIcon);
