// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MoreHorizIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="more-horiz-0" d="M4 6v3h-3v-3zM6 6v3h3v-3zM11 6v3h3v-3z" /></g>
    </SVGIcon>
  );
});

MoreHorizIcon.displayName = 'MoreHorizIcon';

export default MoreHorizIcon;
