// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MoreIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="more-0" d="M9 4h-3v-3h3zM9 6h-3v3h3zM9 11h-3v3h3z" /></g>
    </SVGIcon>
  );
});

MoreIcon.displayName = 'MoreIcon';

export default MoreIcon;
