// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const MoveIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="move-0" d="M10 12v-4c-1.6 0-2.9 0-4 0-4 0-4.8 5.7-4 8-4.3-6-1.1-12 4-12 1.1 0 2.6 0 4 0v-4l6 6-6 6z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  MoveIcon.displayName = 'MoveIcon';
}
export default React.forwardRef(MoveIcon);
