// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const MoveIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="move-0" d="M10 12v-4c-1.6 0-2.9 0-4 0-4 0-4.8 5.7-4 8-4.3-6-1.1-12 4-12 1.1 0 2.6 0 4 0v-4l6 6-6 6z" /></g>
    </SVGIcon>
  );
});

MoveIcon.displayName = 'MoveIcon';

export default MoveIcon;
