// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const NoteOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="note-o-0" d="M15 11v-9c0-0.5-0.5-1-1-1h-12c-0.5 0-1 0.5-1 1v12c0 0.5 0.5 1 1 1h9l4-4zM11 11h2.6l-2.6 2.6c0 0 0-2.6 0-2.6zM14 10h-4v4h-8v-12h12v8z" /></g>
    </SVGIcon>
  );
});

NoteOIcon.displayName = 'NoteOIcon';

export default NoteOIcon;
