// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ObjectCloseOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="object-close-o-0" d="M3 15h4v1h-4c-0.552 0-1-0.448-1-1v0-14c0-0.552 0.448-1 1-1v0h10c0.552 0 1 0.448 1 1v0 6h-1v-6h-10zM5 3h6v4h1v-5h-8v12h3v-1h-2zM13 12l3-3-1-1-3 3-3-3-1 1 3 3-3 3 1 1 3-3 3 3 1-1-2.61-2.61z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ObjectCloseOIcon.displayName = 'ObjectCloseOIcon';
}
export default React.forwardRef(ObjectCloseOIcon);
