// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ObjectAddIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="object-add-0" d="M2 1h12v2h-12zM2 4h10v2h-10zM2 7h8v2h-8zM2 10h4v3.6l-4 1.4zM11.5 11.9l-1.9-1.9-0.6 0.6 1.9 1.9-1.9 1.9 0.6 0.6 1.9-1.9 1.9 1.9 0.6-0.6-1.9-1.9 1.9-1.9-0.6-0.6z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ObjectAddIcon.displayName = 'ObjectAddIcon';
}
export default React.forwardRef(ObjectAddIcon);
