// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ObjectAddIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="object-add-0" d="M2 1h12v2h-12zM2 4h10v2h-10zM2 7h8v2h-8zM2 10h4v3.6l-4 1.4zM11.5 11.9l-1.9-1.9-0.6 0.6 1.9 1.9-1.9 1.9 0.6 0.6 1.9-1.9 1.9 1.9 0.6-0.6-1.9-1.9 1.9-1.9-0.6-0.6z" /></g>
    </SVGIcon>
  );
});

ObjectAddIcon.displayName = 'ObjectAddIcon';

export default ObjectAddIcon;
