// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M3 3h4v10h-4v-10zM9 3h4v10h-4v-10z" />,
  'PauseIcon',
);
