// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const PauseIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="pause-0" d="M3 3h4v10h-4v-10zM9 3h4v10h-4v-10z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  PauseIcon.displayName = 'PauseIcon';
}
export default React.forwardRef(PauseIcon);
