// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const PlanAddIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="plan-add-0" d="M13 11h3v2h-3v3h-2v-3h-3v-2h3v-3h2v3zM1 7c0.6 0 1-0.4 1-1s-0.4-1-1-1-1 0.4-1 1c0 0.6 0.4 1 1 1zM3 2c-0.6 0-1 0.4-1 1s0.4 1 1 1 1-0.4 1-1c0-0.6-0.4-1-1-1zM6 0c-0.6 0-1 0.4-1 1s0.4 1 1 1 1-0.4 1-1c0-0.6-0.4-1-1-1zM10 2c0.6 0 1-0.4 1-1s-0.4-1-1-1-1 0.4-1 1c0 0.6 0.4 1 1 1zM13 4c0.6 0 1-0.4 1-1s-0.4-1-1-1-1 0.4-1 1c0 0.6 0.4 1 1 1zM15 7c0.6 0 1-0.4 1-1s-0.4-1-1-1-1 0.4-1 1c0 0.6 0.4 1 1 1zM1 9c-0.6 0-1 0.4-1 1s0.4 1 1 1 1-0.4 1-1c0-0.6-0.4-1-1-1zM3 12c-0.6 0-1 0.4-1 1s0.4 1 1 1 1-0.4 1-1c0-0.6-0.4-1-1-1zM6 14c-0.6 0-1 0.4-1 1s0.4 1 1 1 1-0.4 1-1c0-0.6-0.4-1-1-1z" /></g>
    </SVGIcon>
  );
});

PlanAddIcon.displayName = 'PlanAddIcon';

export default PlanAddIcon;
