// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const PlanStatusIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="plan-status-0" d="M8 0v8l4.3 4.8c-1.2 1-2.7 1.7-4.3 1.7-3.6 0-6.5-2.9-6.5-6.5 0-3.3 2.4-5.9 5.5-6.4v-1.5c-3.9 0.5-7 3.8-7 7.9 0 4.4 3.6 8 8 8 2.1 0 3.9-0.8 5.3-2.1 1.7-1.4 2.7-3.5 2.7-5.9 0-4.4-3.6-8-8-8z" /></g>
    </SVGIcon>
  );
});

PlanStatusIcon.displayName = 'PlanStatusIcon';

export default PlanStatusIcon;
