// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M3 2v12l10-6-10-6z" />,
  'PlayIcon',
);
