// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const PlaybookIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="playbook-0" d="M1 0v16h14v-16h-14zM14 15h-12v-14h12v14zM7.3 8.6h-2.3l0.6-5.6h3.6l-1.2 3.8h3l-4.2 6.2 0.5-4.4z" /></g>
    </SVGIcon>
  );
});

PlaybookIcon.displayName = 'PlaybookIcon';

export default PlaybookIcon;
