// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const PositiveTrueIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="positive-true-0" d="M11.9 14.2l-1.5-1.4-0.4 0.3 1.9 1.9 4.1-4.9-0.4-0.3zM14 2l-8.1 9.8-3.9-3.8-2 2 6 6 10-12z" /></g>
    </SVGIcon>
  );
});

PositiveTrueIcon.displayName = 'PositiveTrueIcon';

export default PositiveTrueIcon;
