// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const PositiveTrueIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="positive-true-0" d="M11.9 14.2l-1.5-1.4-0.4 0.3 1.9 1.9 4.1-4.9-0.4-0.3zM14 2l-8.1 9.8-3.9-3.8-2 2 6 6 10-12z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  PositiveTrueIcon.displayName = 'PositiveTrueIcon';
}
export default React.forwardRef(PositiveTrueIcon);
