// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const PositiveBenigntrueIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="positive-benigntrue-0" d="M15.6 10l-2.1 2.1-2.1-2.1-0.4 0.4 2.1 2.1-2.1 2.1 0.4 0.4 2.1-2.1 2.1 2.1 0.4-0.4-2.1-2.1 2.1-2.1zM14 1l-8.1 9.8-3.9-3.8-2 2 6 6 10-12zM6 14l-5-5 1-1 3.4 3.3 0.5 0.5 0.5-0.6 7.6-9.2 1 1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  PositiveBenigntrueIcon.displayName = 'PositiveBenigntrueIcon';
}
export default React.forwardRef(PositiveBenigntrueIcon);
