// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const PrintIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="print-0" d="M15 6h-14c-0.552 0-1 0.448-1 1v0 5h3v3c0 0.552 0.448 1 1 1v0h8c0.552 0 1-0.448 1-1v0-3h3v-5c0-0.552-0.448-1-1-1v0zM12 12v3h-8v-5h8v2zM15 8h-1v-1h1v1zM13 1c0-0.552-0.448-1-1-1v0h-8c-0.552 0-1 0.448-1 1v0 4h10v-4zM12 4h-8v-3h8v3z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  PrintIcon.displayName = 'PrintIcon';
}
export default React.forwardRef(PrintIcon);
