// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const RegistryIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="registry-0" d="M0 3h6v6h-6zM0 16h6v-6h-6zM7 16h6v-6h-6zM15 1h-3v3h3zM13 5l-2 2 2 2 2-2zM11 4l-2-2-2 2 2 2z" /></g>
    </SVGIcon>
  );
});

RegistryIcon.displayName = 'RegistryIcon';

export default RegistryIcon;
