// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ReorderIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="reorder-0" d="M10 12v-10h2v10h2l-3 4-3-4h2zM8 4l-3-4-3 4h2v10h2v-10h2z" /></g>
    </SVGIcon>
  );
});

ReorderIcon.displayName = 'ReorderIcon';

export default ReorderIcon;
