// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ReplyIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="reply-0" d="M14 16c0.8-2.3 0-8-4-8-1.1 0-2.4 0-4 0v4l-6-6 6-6v4c1.4 0 2.9 0 4 0 5.1 0 8.3 6 4 12z" /></g>
    </SVGIcon>
  );
});

ReplyIcon.displayName = 'ReplyIcon';

export default ReplyIcon;
