// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ResizeNwseIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="resize-nwse-0" d="M15 9v6h-6l2.3-2.3-8-8-2.3 2.3v-6h6l-2.3 2.3 8 8 2.3-2.3z" /></g>
    </SVGIcon>
  );
});

ResizeNwseIcon.displayName = 'ResizeNwseIcon';

export default ResizeNwseIcon;
