// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ResizeNeswIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="resize-nesw-0" d="M12.7 4.7l-8 8 2.3 2.3h-6v-6l2.3 2.3 8-8-2.3-2.3h6v6l-2.3-2.3z" /></g>
    </SVGIcon>
  );
});

ResizeNeswIcon.displayName = 'ResizeNeswIcon';

export default ResizeNeswIcon;
