// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ResizeHorizontalIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="resize-horizontal-0" d="M15 9h-6v4h2l-3 3-3-3h2v-4h-6v-2h6v-4h-2l3-3 3 3h-2v4h6z" /></g>
    </SVGIcon>
  );
});

ResizeHorizontalIcon.displayName = 'ResizeHorizontalIcon';

export default ResizeHorizontalIcon;
