// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ResizeNwseIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="resize-nwse-0" d="M15 9v6h-6l2.3-2.3-8-8-2.3 2.3v-6h6l-2.3 2.3 8 8 2.3-2.3z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ResizeNwseIcon.displayName = 'ResizeNwseIcon';
}
export default React.forwardRef(ResizeNwseIcon);
