// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ResizeNwseIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="resize-nwse-0" d="M15 9v6h-6l2.3-2.3-8-8-2.3 2.3v-6h6l-2.3 2.3 8 8 2.3-2.3z" /></g>
    </SVGIcon>
  );
});

ResizeNwseIcon.displayName = 'ResizeNwseIcon';

export default ResizeNwseIcon;
