// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ResizeNeswIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="resize-nesw-0" d="M12.7 4.7l-8 8 2.3 2.3h-6v-6l2.3 2.3 8-8-2.3-2.3h6v6l-2.3-2.3z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ResizeNeswIcon.displayName = 'ResizeNeswIcon';
}
export default React.forwardRef(ResizeNeswIcon);
