// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SaveOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="save-o-0" d="M11 1h-9c-0.6 0-1 0.4-1 1v12c0 0.6 0.4 1 1 1h12c0.6 0 1-0.4 1-1v-9l-4-4zM8 2v2h1v-2h1v3h-6v-3h4zM14 14h-12v-12h1v4h8v-3.6l3 3v8.6zM3 13h10v-5h-10v5zM4 9h8v3h-8v-3z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SaveOIcon.displayName = 'SaveOIcon';
}
export default React.forwardRef(SaveOIcon);
