// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ScanSquareIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="scan-square-0" d="M2 5h-1v-2.5c0-0.828 0.672-1.5 1.5-1.5v0h2.5v1h-2.5c-0.276 0-0.5 0.224-0.5 0.5v0zM2 13.5v-2.5h-1v2.5c0 0.828 0.672 1.5 1.5 1.5v0h2.5v-1h-2.5c-0.276 0-0.5-0.224-0.5-0.5v0zM14 2.5v2.5h1v-2.5c0-0.828-0.672-1.5-1.5-1.5v0h-2.5v1h2.5c0.276 0 0.5 0.224 0.5 0.5v0zM14 13.5c0 0.276-0.224 0.5-0.5 0.5v0h-2.5v1h2.5c0.828 0 1.5-0.672 1.5-1.5v0-2.5h-1zM0 7v2h16v-2z" /></g>
    </SVGIcon>
  );
});

ScanSquareIcon.displayName = 'ScanSquareIcon';

export default ScanSquareIcon;
