// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ScanSquareIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="scan-square-0" d="M2 5h-1v-2.5c0-0.828 0.672-1.5 1.5-1.5v0h2.5v1h-2.5c-0.276 0-0.5 0.224-0.5 0.5v0zM2 13.5v-2.5h-1v2.5c0 0.828 0.672 1.5 1.5 1.5v0h2.5v-1h-2.5c-0.276 0-0.5-0.224-0.5-0.5v0zM14 2.5v2.5h1v-2.5c0-0.828-0.672-1.5-1.5-1.5v0h-2.5v1h2.5c0.276 0 0.5 0.224 0.5 0.5v0zM14 13.5c0 0.276-0.224 0.5-0.5 0.5v0h-2.5v1h2.5c0.828 0 1.5-0.672 1.5-1.5v0-2.5h-1zM0 7v2h16v-2z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  ScanSquareIcon.displayName = 'ScanSquareIcon';
}
export default React.forwardRef(ScanSquareIcon);
