// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ScreenshotIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="screenshot-0" d="M16 13.5h-2.5v2.5h-1.5v-2.5h-9.5v-9.475h-2.492v-1.5h2.492v-2.525h1.5v2.525h9.508v1.5h-0.008v6.975h-1.5v-6.975h-8v7.975h12z" /></g>
    </SVGIcon>
  );
});

ScreenshotIcon.displayName = 'ScreenshotIcon';

export default ScreenshotIcon;
