// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SearchOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="search-o-0" d="M16 14.59l-4.26-4.26c0.787-1.064 1.259-2.403 1.259-3.851 0-3.601-2.919-6.52-6.52-6.52s-6.52 2.919-6.52 6.52c0 3.601 2.919 6.52 6.52 6.52 1.449 0 2.787-0.472 3.869-1.271l-0.018 0.013 4.26 4.26zM6.5 11.5c-2.761 0-5-2.239-5-5s2.239-5 5-5c2.761 0 5 2.239 5 5v0c0 2.761-2.239 5-5 5v0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SearchOIcon.displayName = 'SearchOIcon';
}
export default React.forwardRef(SearchOIcon);
