// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SelfServiceIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="self-service-0" d="M16 0h-12c-2.2 0-4 1.8-4 4v12l3-2c0 0 0.5 0 1 0h8c2.2 0 4-1.8 4-4v-10zM9 12h-2v-2h2v2zM11.1 4.6v0c0 0.5-0.2 0.9-0.5 1.2-0.5 0.4-1.6 1.3-1.6 2.2v1h-2v-1c0-0.8 1-1.8 1-1.8v0c0.4-0.4 0.8-0.7 1.2-1.1v0c0.1-0.2 0.2-0.4 0.2-0.6v0c0-0.3 0-1.2-1.4-1.2s-1.4 0.8-1.5 1.3h-1.5c0-0.7 0.3-1.4 0.8-1.8v0 0 0c0.6-0.5 1.3-0.8 2-0.8 0.1 0 0.2 0 0.2 0 0.1 0 0.1 0 0.2 0 0.8 0 1.5 0.3 2.1 0.7v0c0.5 0.5 0.8 1.1 0.8 1.9v0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SelfServiceIcon.displayName = 'SelfServiceIcon';
}
export default React.forwardRef(SelfServiceIcon);
