// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE
import React from 'react';
import createSVGIcon from '../utils/createSVGIcon';

export default createSVGIcon(
  <path d="M0 0l1 6 10 2-10 2-1 6 16-8-16-8z" />,
  'SendIcon',
);
