// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const ServerAddIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="server-add-0" d="M14 3v-3h-14v3zM2 1h3v1h-3zM14 7v-3h-14v3zM2 5h3v1h-3zM16 13h-3v3h-2v-3h-3v-2h3v-3h2v3h3zM0 8v3h6v-1h3v-2zM5 10h-3v-1h3z" /></g>
    </SVGIcon>
  );
});

ServerAddIcon.displayName = 'ServerAddIcon';

export default ServerAddIcon;
