// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SpamWarningIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="spam-warning-0" d="M14.98 0h-13.96c-0.56 0-1.020 0.46-1.020 1.020v11.97c0 0.56 0.46 1.020 1.020 1.020h6.4c-0.27-0.61-0.42-1.29-0.42-2 0-2.76 2.24-5 5-5 1.64 0 3.090 0.8 4 2.030v-8.020c0-0.56-0.46-1.020-1.020-1.020zM7.94 6.75l-5.94-4.5h12l-6.060 4.5zM12 8c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4zM13 14.5h-2v-1h2v1zM13 12.5h-2v-3h2v3z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SpamWarningIcon.displayName = 'SpamWarningIcon';
}
export default React.forwardRef(SpamWarningIcon);
