// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SpamIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="spam-0" d="M14.98 0h-13.96c-0.56 0-1.020 0.46-1.020 1.020v11.97c0 0.56 0.46 1.020 1.020 1.020h13.96c0.56 0 1.020-0.46 1.020-1.020v-11.97c0-0.56-0.46-1.020-1.020-1.020zM7.94 6.75l-5.94-4.5h12l-6.060 4.5z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SpamIcon.displayName = 'SpamIcon';
}
export default React.forwardRef(SpamIcon);
