// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SpinnerIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="spinner-0" d="M16 8c-0.001 4.417-3.582 7.998-8 7.998s-8-3.582-8-8c0-3.888 2.773-7.128 6.449-7.85l0.051-0.008v1.54c-2.889 0.702-5 3.267-5 6.325 0 3.59 2.91 6.5 6.5 6.5s6.5-2.91 6.5-6.5c0-3.058-2.111-5.622-4.956-6.315l-0.044-0.009v-1.54c3.727 0.73 6.5 3.97 6.5 7.858 0 0.001 0 0.001 0 0.002v-0z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SpinnerIcon.displayName = 'SpinnerIcon';
}
export default React.forwardRef(SpinnerIcon);
