// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const StarIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="star-0" d="M12.008 10.21l0.945 5.79-4.953-2.735-4.952 2.735 0.945-5.79-3.993-4.088 5.519-0.842 2.481-5.28 2.481 5.28 5.519 0.842z" /></g>
    </SVGIcon>
  );
});

StarIcon.displayName = 'StarIcon';

export default StarIcon;
