// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const StarOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="star-o-0" d="M8 2.351l1.803 3.837 4.121 0.629-2.984 3.056 0.695 4.257-3.634-2.007-3.633 2.007 0.695-4.257-2.985-3.056 4.121-0.629 1.803-3.837zM8 0l-2.481 5.28-5.519 0.842 3.993 4.088-0.945 5.79 4.952-2.735 4.953 2.735-0.945-5.79 3.992-4.088-5.519-0.842-2.481-5.28z" /></g>
    </SVGIcon>
  );
});

StarOIcon.displayName = 'StarOIcon';

export default StarOIcon;
