// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const StarIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="star-0" d="M12.008 10.21l0.945 5.79-4.953-2.735-4.952 2.735 0.945-5.79-3.993-4.088 5.519-0.842 2.481-5.28 2.481 5.28 5.519 0.842z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  StarIcon.displayName = 'StarIcon';
}
export default React.forwardRef(StarIcon);
