// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const SunIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="sun-0" d="M8.75 0h-1.5v2h1.5v-2z" />,<path key="sun-1" d="M8.75 14h-1.5v2h1.5v-2z" />,<path key="sun-2" d="M2.873 1.813l-1.060 1.060 1.414 1.415 1.061-1.061-1.415-1.414z" />,<path key="sun-3" d="M12.773 11.712l-1.061 1.061 1.415 1.414 1.060-1.060-1.414-1.415z" />,<path key="sun-4" d="M2 7.25h-2v1.5h2v-1.5z" />,<path key="sun-5" d="M16 7.25h-2v1.5h2v-1.5z" />,<path key="sun-6" d="M3.227 11.712l-1.414 1.415 1.060 1.060 1.415-1.414-1.061-1.061z" />,<path key="sun-7" d="M13.127 1.813l-1.415 1.414 1.061 1.061 1.414-1.415-1.060-1.060z" />,<path key="sun-8" d="M12.75 8c0 2.623-2.127 4.75-4.75 4.75s-4.75-2.127-4.75-4.75c0-2.623 2.127-4.75 4.75-4.75s4.75 2.127 4.75 4.75z" /></g>
    </SVGIcon>
  );
});

SunIcon.displayName = 'SunIcon';

export default SunIcon;
