// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SunOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="sun-o-0" d="M8 4.75c1.795 0 3.25 1.455 3.25 3.25s-1.455 3.25-3.25 3.25c-1.795 0-3.25-1.455-3.25-3.25v0c0.002-1.794 1.456-3.248 3.25-3.25h0zM8 3.25c-2.623 0-4.75 2.127-4.75 4.75s2.127 4.75 4.75 4.75c2.623 0 4.75-2.127 4.75-4.75v0c0-2.623-2.127-4.75-4.75-4.75v0z" />,<path key="sun-o-1" d="M8.75 0h-1.5v2h1.5v-2z" />,<path key="sun-o-2" d="M8.75 14h-1.5v2h1.5v-2z" />,<path key="sun-o-3" d="M2.873 1.813l-1.060 1.060 1.414 1.415 1.061-1.061-1.415-1.414z" />,<path key="sun-o-4" d="M12.773 11.712l-1.061 1.061 1.415 1.414 1.060-1.060-1.414-1.415z" />,<path key="sun-o-5" d="M2 7.25h-2v1.5h2v-1.5z" />,<path key="sun-o-6" d="M16 7.25h-2v1.5h2v-1.5z" />,<path key="sun-o-7" d="M3.227 11.712l-1.414 1.415 1.060 1.060 1.415-1.414-1.061-1.061z" />,<path key="sun-o-8" d="M13.127 1.813l-1.415 1.414 1.061 1.061 1.414-1.415-1.060-1.060z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  SunOIcon.displayName = 'SunOIcon';
}
export default React.forwardRef(SunOIcon);
