// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const SyncIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="sync-0" d="M14 8v2c-0.001 0.552-0.448 0.999-1 1h-7.002l0.002-2-4 3 4 3-0.002-2h7.002c1.656-0.002 2.998-1.344 3-3v-2zM2 6c0-0.552 0.448-1 1-1h7v2l3.996-3-3.996-3v2h-7c-1.656 0.001-2.999 1.344-3 3v2h2z" /></g>
    </SVGIcon>
  );
});

SyncIcon.displayName = 'SyncIcon';

export default SyncIcon;
