// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const TaskOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="task-o-0" d="M14 1h-2v-1h-8v1h-2c-0.552 0-1 0.448-1 1v0 13c0 0.552 0.448 1 1 1v0h12c0.552 0 1-0.448 1-1v0-13c0-0.552-0.448-1-1-1v0zM5 1h6v1h-6v-1zM14 15h-12v-13h2v1h8v-1h2v13zM9 7h4v1h-4v-1zM9 11h4v1h-4v-1zM7.67 4.63l0.7 0.7-3.37 3.38-2-2 0.7-0.71 1.3 1.29zM7.67 8.63l0.7 0.7-3.37 3.38-2-2 0.7-0.71 1.3 1.29z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  TaskOIcon.displayName = 'TaskOIcon';
}
export default React.forwardRef(TaskOIcon);
