// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const TaskAddOIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="task-add-o-0" d="M16 11v2h-3v3h-2v-3h-3v-2h3v-3h2v3h3zM2 15h8v1h-8c-0.552 0-1-0.448-1-1v0-13c0-0.552 0.448-1 1-1v0h2v-1h8v1h2c0.552 0 1 0.448 1 1v0 8h-1v-8h-2v1h-8v-1h-2v13zM5 1v1h6v-1h-6z" /></g>
    </SVGIcon>
  );
});

TaskAddOIcon.displayName = 'TaskAddOIcon';

export default TaskAddOIcon;
