// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const TaskIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="task-0" d="M14 1h-1v2h-10v-2h-1c-0.552 0-1 0.448-1 1v0 13c0 0.552 0.448 1 1 1v0h12c0.552 0 1-0.448 1-1v0-13c0-0.552-0.448-1-1-1v0zM12 11h-8v-1h8v1zM12 9h-8v-1h8v1zM12 7h-8v-1h8v1zM12 2h-8v-2h8v2z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  TaskIcon.displayName = 'TaskIcon';
}
export default React.forwardRef(TaskIcon);
