// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const TaskCloseOIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="task-close-o-0" d="M15.86 14.83l0.14 0.17-1 1-1-1v-0.060l-1-0.94-1-1-3 3-1-1 3-3-3-3 1-1 3 3 3-3 1 1-3 3 2 2zM2 15h5v1h-5c-0.552 0-1-0.448-1-1v0-13c0-0.552 0.448-1 1-1v0h2v-1h8v1h2c0.552 0 1 0.448 1 1v0 5h-1v-5h-2v1h-8v-1h-2v13zM5 2h6v-1h-6v1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  TaskCloseOIcon.displayName = 'TaskCloseOIcon';
}
export default React.forwardRef(TaskCloseOIcon);
