// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const ThumbtackIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="thumbtack-0" d="M16 4.6l-1.1 1.1c-0.4 0.4-1 0.4-1.4 0 0 0 0 0 0 0l-0.4-0.4-2.5 3.3 0.6 0.6c0.8 0.8 0.8 2 0 2.8l-1 1-7.2-7.2 1-1c0.8-0.8 2-0.8 2.8 0 0 0 0 0 0 0l0.6 0.6 3.3-2.4-0.4-0.4c-0.4-0.4-0.4-1 0-1.4 0 0 0 0 0 0l1.1-1.2 4.6 4.6zM0.1 15.5c-0.1 0.1-0.1 0.3 0 0.4s0.3 0.1 0.4 0l6.2-5-1.6-1.6-5 6.2z" /></g>
    </SVGIcon>
  );
});

ThumbtackIcon.displayName = 'ThumbtackIcon';

export default ThumbtackIcon;
