// GENERATED BY src/generate.mjs
// DO NOT EDIT THIS FILE

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const TimeOffIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="time-off-0" d="M16 8c0-4.4-3.6-8-8-8-2 0-3.6 0.8-5 2l-2-2-1 1 15 15 1-1-2-2c1.2-1.4 2-3 2-5zM10 9h3v-1h-4l-1-1v-4h-1v3l-3-3c1.1-0.9 2.5-1.5 4-1.5 3.6 0 6.5 2.9 6.5 6.5 0 1.5-0.6 2.9-1.5 4l-3-3zM8 14.5v0c-3.6 0-6.5-2.9-6.5-6.5 0-1 0.1-2.1 0.5-3l-1-1c-0.7 1.2-1 2.6-1 4 0 4.4 3.6 8 8 8 1.4 0 2.8-0.3 4-1l-1-1c-0.9 0.4-2 0.5-3 0.5z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  TimeOffIcon.displayName = 'TimeOffIcon';
}
export default React.forwardRef(TimeOffIcon);
