// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const UserCloseIcon = forwardRef((
  {
    spin = false,
    ...props
  },
  ref,
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="user-close-0" d="M9.586 12l-1.996 2h-5.378c-4.005 0-1.572-3.5-0.425-4.666 0.996-1.006 2.25-1.754 3.656-2.136l0.057-0.013v-0.534c-1.192-0.575-2-1.774-2-3.162 0-1.933 1.567-3.5 3.5-3.5s3.5 1.567 3.5 3.5c0 1.388-0.808 2.587-1.979 3.153l-0.021 0.009v0.436l-1.914 1.914zM14.986 13.986l-1.986-1.986 3-3-1-1-3 3-3-3-1 1 3 3-3 3 1 1 3-3 3 3 1-1-0.166-0.166z" /></g>
    </SVGIcon>
  );
});

UserCloseIcon.displayName = 'UserCloseIcon';

export default UserCloseIcon;
