// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const UserIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="user-0" d="M13.472 16h-10.944c-4.577 0-1.796-4-0.485-5.333 1.138-1.15 2.572-2.005 4.178-2.441l0.065-0.015v-0.61c-1.362-0.657-2.286-2.028-2.286-3.614 0-2.209 1.791-4 4-4s4 1.791 4 4c0 1.586-0.923 2.957-2.262 3.604l-0.024 0.010v0.61c1.671 0.452 3.105 1.307 4.243 2.456l0.001 0.001c1.311 1.333 4.092 5.333-0.485 5.333z" /></g>
    </SVGIcon>
  );
});

UserIcon.displayName = 'UserIcon';

export default UserIcon;
