// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const WarningCircleIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="warning-circle-0" d="M8 0c-4.418 0-8 3.582-8 8s3.582 8 8 8c4.418 0 8-3.582 8-8v0c0-4.418-3.582-8-8-8v0zM9 13h-2v-2h2zM9 10h-2v-6h2z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  WarningCircleIcon.displayName = 'WarningCircleIcon';
}
export default React.forwardRef(WarningCircleIcon);
