// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const WifiIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="wifi-0" d="M12.8 8.5l-1.6 1.2c-0.7-1-1.9-1.7-3.2-1.7s-2.5 0.7-3.3 1.7l-1.5-1.2c1.1-1.5 2.8-2.5 4.8-2.5s3.7 1 4.8 2.5zM1.6 7.2c1.4-1.9 3.8-3.2 6.4-3.2s5 1.3 6.4 3.2l1.6-1.2c-1.8-2.4-4.7-4-8-4s-6.2 1.6-8 4l1.6 1.2zM8 14c1.1 0 2-0.9 2-2s-0.9-2-2-2-2 0.9-2 2 0.9 2 2 2z" /></g>
    </SVGIcon>
  );
});

WifiIcon.displayName = 'WifiIcon';

export default WifiIcon;
