// AUTO-GENERATED BY "scripts/generate-icons.mjs"
// DO NOT MODIFY THIS FILE

import React, { forwardRef } from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { useIconStyle } from '../styles';

const WineventIcon = forwardRef((
  {
    spin = false,
    sx,
    ...rest
  },
  ref,
) => {
  const styleProps = useIconStyle({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      sx={[
        styleProps,
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
      {...rest}
    >
      <g><path key="winevent-0" d="M14.5 1h-1.5v-0.5c-0.001-0.276-0.224-0.499-0.5-0.5h-11c-0.276 0.001-0.499 0.224-0.5 0.5v15c0.001 0.276 0.224 0.499 0.5 0.5h13c0.276-0.001 0.499-0.224 0.5-0.5v-14c-0.001-0.276-0.224-0.499-0.5-0.5h-0zM3 4h8v1h-8zM3 7h8v1h-8zM3 10h8v1h-8zM14 15h-12l1-1h10v-11l1-1z" /></g>
    </SVGIcon>
  );
});

WineventIcon.displayName = 'WineventIcon';

export default WineventIcon;
