// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const WineventIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="winevent-0" d="M14.5 1h-1.5v-0.5c-0.001-0.276-0.224-0.499-0.5-0.5h-11c-0.276 0.001-0.499 0.224-0.5 0.5v15c0.001 0.276 0.224 0.499 0.5 0.5h13c0.276-0.001 0.499-0.224 0.5-0.5v-14c-0.001-0.276-0.224-0.499-0.5-0.5h-0zM3 4h8v1h-8zM3 7h8v1h-8zM3 10h8v1h-8zM14 15h-12l1-1h10v-11l1-1z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  WineventIcon.displayName = 'WineventIcon';
}
export default React.forwardRef(WineventIcon);
