// GENERATED BY icon/generate.js
// DON NOT EDIT IT MANUALLY

import * as React from 'react';
import { SVGIcon } from '@tonic-ui/react';
import { getIconStyleProps } from '../utils';

const WmiIcon = (
  {
    spin = false,
    ...props
  },
  ref
) => {
  const styleProps = getIconStyleProps({ spin });
  return (
    <SVGIcon
      ref={ref}
      viewBox="0 0 16 16"
      {...styleProps}
      {...props}
    >
      <g><path key="wmi-0" d="M15 4h-4v-4zM10 5h5v10.417c-0.006 0.323-0.269 0.583-0.594 0.583-0.002 0-0.005-0-0.007-0h-12.8c-0.002 0-0.004 0-0.006 0-0.324 0-0.588-0.26-0.594-0.583v-14.834c0.006-0.323 0.269-0.583 0.593-0.583 0.002 0 0.005 0 0.007 0h8.4zM12 10l-1.4 2.8 0.9 0.4 1.6-3.2-1.6-3.2-0.9 0.4zM5.5 12.8l-1.4-2.8 1.3-2.8-0.9-0.4-1.6 3.2 1.7 3.2zM9.5 6.1l-1-0.2-2 8 1 0.2z" /></g>
    </SVGIcon>
  );
};

if (process.env.NODE_ENV !== 'production') {
  WmiIcon.displayName = 'WmiIcon';
}
export default React.forwardRef(WmiIcon);
