const iconList = {
  iconsets: [{
    id: 0,
    name: 'Utility Icons'
  }, {
    id: 1,
    name: 'Device Icons'
  }, {
    id: 7,
    name: 'File Icons'
  }, {
    id: 6,
    name: 'Edit Icons'
  }, {
    id: 5,
    name: 'Direction Icons'
  }, {
    id: 4,
    name: 'Chart Icons'
  }, {
    id: 3,
    name: 'Severity Icons'
  }, {
    id: 2,
    name: 'Branding Icons'
  }, {
    id: 8,
    name: 'Threat Type'
  }],
  icons: [{
    code: 'e000',
    iconset: 0,
    name: 'add',
    new: false
  }, {
    code: 'e0b7',
    iconset: 0,
    name: 'add-circle-o',
    new: false
  }, {
    code: 'e001',
    iconset: 0,
    name: 'add-group',
    new: false
  }, {
    code: 'e003',
    iconset: 0,
    name: 'add-square-o',
    new: false
  }, {
    code: 'e0d2',
    iconset: 0,
    name: 'add-square-plus-o',
    new: true
  }, {
    code: 'e002',
    iconset: 0,
    name: 'address',
    new: false
  }, {
    code: 'e004',
    iconset: 0,
    name: 'alert',
    new: false
  }, {
    code: 'ea00',
    iconset: 6,
    name: 'align-center',
    new: false
  }, {
    code: 'ea01',
    iconset: 6,
    name: 'align-left',
    new: false
  }, {
    code: 'ea02',
    iconset: 6,
    name: 'align-right',
    new: false
  }, {
    code: 'ed01',
    iconset: 2,
    name: 'android',
    new: false
  }, {
    code: 'e919',
    iconset: 5,
    name: 'angle-down',
    new: false
  }, {
    code: 'e900',
    iconset: 5,
    name: 'angle-left',
    new: false
  }, {
    code: 'e901',
    iconset: 5,
    name: 'angle-right',
    new: false
  }, {
    code: 'e91a',
    iconset: 5,
    name: 'angle-up',
    new: false
  }, {
    code: 'e0af',
    iconset: 0,
    name: 'app',
    new: false
  }, {
    code: 'ed02',
    iconset: 2,
    name: 'apple',
    new: false
  }, {
    code: 'e902',
    iconset: 5,
    name: 'arrow-down',
    new: false
  }, {
    code: 'e903',
    iconset: 5,
    name: 'arrow-left',
    new: false
  }, {
    code: 'e904',
    iconset: 5,
    name: 'arrow-long-left',
    new: false
  }, {
    code: 'e905',
    iconset: 5,
    name: 'arrow-long-right',
    new: false
  }, {
    code: 'e906',
    iconset: 5,
    name: 'arrow-right',
    new: false
  }, {
    code: 'e907',
    iconset: 5,
    name: 'arrow-up',
    new: false
  }, {
    code: 'e91b',
    iconset: 5,
    name: 'arrows',
    new: false
  }, {
    code: 'e088',
    iconset: 0,
    name: 'asterisk',
    new: false
  }, {
    code: 'e005',
    iconset: 0,
    name: 'attach',
    new: false
  }, {
    code: 'e006',
    iconset: 0,
    name: 'attach-alert',
    new: false
  }, {
    code: 'e007',
    iconset: 0,
    name: 'attach-file',
    new: false
  }, {
    code: 'e008',
    iconset: 0,
    name: 'attach-new',
    new: false
  }, {
    code: 'e009',
    iconset: 0,
    name: 'backup',
    new: false
  }, {
    code: 'e00a',
    iconset: 0,
    name: 'blacklist',
    new: false
  }, {
    code: 'e00b',
    iconset: 0,
    name: 'block',
    new: false
  }, {
    code: 'e500',
    iconset: 8,
    name: 'block-app',
    new: true
  }, {
    code: 'ea03',
    iconset: 6,
    name: 'bold',
    new: false
  }, {
    code: 'e0cb',
    iconset: 0,
    name: 'bolt',
    new: false
  }, {
    code: 'e00c',
    iconset: 0,
    name: 'bookmark',
    new: false
  }, {
    code: 'e00d',
    iconset: 0,
    name: 'box-in',
    new: false
  }, {
    code: 'e00e',
    iconset: 0,
    name: 'box-out',
    new: false
  }, {
    code: 'e0c2',
    iconset: 0,
    name: 'box-upload',
    new: false
  }, {
    code: 'e089',
    iconset: 0,
    name: 'bug',
    new: false
  }, {
    code: 'e0b2',
    iconset: 0,
    name: 'build',
    new: false
  }, {
    code: 'e00f',
    iconset: 0,
    name: 'calendar',
    new: false
  }, {
    code: 'e08a',
    iconset: 0,
    name: 'calendar-empty',
    new: false
  }, {
    code: 'e501',
    iconset: 8,
    name: 'callback',
    new: true
  }, {
    code: 'e61c',
    iconset: 1,
    name: 'camera',
    new: false
  }, {
    code: 'e908',
    iconset: 5,
    name: 'caret-down',
    new: false
  }, {
    code: 'e909',
    iconset: 5,
    name: 'caret-left',
    new: false
  }, {
    code: 'e90a',
    iconset: 5,
    name: 'caret-right',
    new: false
  }, {
    code: 'e910',
    iconset: 5,
    name: 'caret-right-down',
    new: false
  }, {
    code: 'e90b',
    iconset: 5,
    name: 'caret-right-o',
    new: false
  }, {
    code: 'e90c',
    iconset: 5,
    name: 'caret-square-down',
    new: false
  }, {
    code: 'e90d',
    iconset: 5,
    name: 'caret-square-left',
    new: false
  }, {
    code: 'e90e',
    iconset: 5,
    name: 'caret-square-right',
    new: false
  }, {
    code: 'e90f',
    iconset: 5,
    name: 'caret-square-up',
    new: false
  }, {
    code: 'e911',
    iconset: 5,
    name: 'caret-up',
    new: false
  }, {
    code: 'e08b',
    iconset: 0,
    name: 'cart',
    new: false
  }, {
    code: 'e800',
    iconset: 4,
    name: 'chart-area',
    new: false
  }, {
    code: 'e801',
    iconset: 4,
    name: 'chart-bar',
    new: false
  }, {
    code: 'e806',
    iconset: 4,
    name: 'chart-dot',
    new: false
  }, {
    code: 'e802',
    iconset: 4,
    name: 'chart-line',
    new: false
  }, {
    code: 'e803',
    iconset: 4,
    name: 'chart-pie',
    new: false
  }, {
    code: 'e804',
    iconset: 4,
    name: 'chart-table',
    new: false
  }, {
    code: 'e807',
    iconset: 4,
    name: 'chart_areastep',
    new: false
  }, {
    code: 'e808',
    iconset: 4,
    name: 'chart_donut',
    new: false
  }, {
    code: 'e809',
    iconset: 4,
    name: 'chart_scatter',
    new: false
  }, {
    code: 'e010',
    iconset: 0,
    name: 'check',
    new: false
  }, {
    code: 'e08c',
    iconset: 0,
    name: 'check-bold',
    new: false
  }, {
    code: 'e0b8',
    iconset: 0,
    name: 'check-circle-o',
    new: false
  }, {
    code: 'e011',
    iconset: 0,
    name: 'check-s',
    new: false
  }, {
    code: 'e912',
    iconset: 5,
    name: 'chevron-down',
    new: false
  }, {
    code: 'e913',
    iconset: 5,
    name: 'chevron-left',
    new: false
  }, {
    code: 'e914',
    iconset: 5,
    name: 'chevron-right',
    new: false
  }, {
    code: 'e915',
    iconset: 5,
    name: 'chevron-up',
    new: false
  }, {
    code: 'ed08',
    iconset: 2,
    name: 'chrome',
    new: false
  }, {
    code: 'e012',
    iconset: 0,
    name: 'circle',
    new: false
  }, {
    code: 'e013',
    iconset: 0,
    name: 'circle-dot',
    new: false
  }, {
    code: 'e014',
    iconset: 0,
    name: 'circle-merge',
    new: false
  }, {
    code: 'e015',
    iconset: 0,
    name: 'circle-o',
    new: false
  }, {
    code: 'e016',
    iconset: 0,
    name: 'circle-split',
    new: false
  }, {
    code: 'e08d',
    iconset: 0,
    name: 'city',
    new: false
  }, {
    code: 'e017',
    iconset: 0,
    name: 'clock',
    new: false
  }, {
    code: 'e08e',
    iconset: 0,
    name: 'clock-add',
    new: false
  }, {
    code: 'e018',
    iconset: 0,
    name: 'close',
    new: false
  }, {
    code: 'e0b9',
    iconset: 0,
    name: 'close-circle-o',
    new: false
  }, {
    code: 'e019',
    iconset: 0,
    name: 'close-s',
    new: false
  }, {
    code: 'e08f',
    iconset: 0,
    name: 'cloud',
    new: false
  }, {
    code: 'e090',
    iconset: 0,
    name: 'cloud-off',
    new: false
  }, {
    code: 'e091',
    iconset: 0,
    name: 'cloud-user',
    new: false
  }, {
    code: 'e01a',
    iconset: 0,
    name: 'code',
    new: false
  }, {
    code: 'e91c',
    iconset: 5,
    name: 'collapse-left',
    new: false
  }, {
    code: 'e91d',
    iconset: 5,
    name: 'collapse-right',
    new: false
  }, {
    code: 'e0c3',
    iconset: 0,
    name: 'color',
    new: false
  }, {
    code: 'ea04',
    iconset: 6,
    name: 'colortext',
    new: false
  }, {
    code: 'e0ae',
    iconset: 0,
    name: 'columns',
    new: false
  }, {
    code: 'e01b',
    iconset: 0,
    name: 'comment',
    new: false
  }, {
    code: 'e01c',
    iconset: 0,
    name: 'connect',
    new: false
  }, {
    code: 'e01d',
    iconset: 0,
    name: 'connect-error',
    new: false
  }, {
    code: 'e01e',
    iconset: 0,
    name: 'connect-noip',
    new: false
  }, {
    code: 'e01f',
    iconset: 0,
    name: 'connect-warning',
    new: false
  }, {
    code: 'e0b5',
    iconset: 0,
    name: 'connection',
    new: false
  }, {
    code: 'e020',
    iconset: 0,
    name: 'contact',
    new: false
  }, {
    code: 'e092',
    iconset: 0,
    name: 'crop',
    new: false
  }, {
    code: 'ea05',
    iconset: 6,
    name: 'cut',
    new: false
  }, {
    code: 'e093',
    iconset: 0,
    name: 'database',
    new: false
  }, {
    code: 'e021',
    iconset: 0,
    name: 'date',
    new: false
  }, {
    code: 'e022',
    iconset: 0,
    name: 'delete',
    new: false
  }, {
    code: 'e023',
    iconset: 0,
    name: 'deploy',
    new: false
  }, {
    code: 'e600',
    iconset: 1,
    name: 'desktop',
    new: false
  }, {
    code: 'e601',
    iconset: 1,
    name: 'desktop-add',
    new: false
  }, {
    code: 'e602',
    iconset: 1,
    name: 'desktop-block',
    new: false
  }, {
    code: 'e603',
    iconset: 1,
    name: 'desktop-cloud',
    new: false
  }, {
    code: 'e604',
    iconset: 1,
    name: 'desktop-cloud-down',
    new: false
  }, {
    code: 'e605',
    iconset: 1,
    name: 'desktop-down',
    new: false
  }, {
    code: 'e606',
    iconset: 1,
    name: 'desktop-error',
    new: false
  }, {
    code: 'e607',
    iconset: 1,
    name: 'desktop-group',
    new: false
  }, {
    code: 'e608',
    iconset: 1,
    name: 'desktop-group-cloud',
    new: false
  }, {
    code: 'e609',
    iconset: 1,
    name: 'desktop-hourglass',
    new: false
  }, {
    code: 'e61f',
    iconset: 1,
    name: 'desktop-off',
    new: false
  }, {
    code: 'e60a',
    iconset: 1,
    name: 'desktop-update',
    new: false
  }, {
    code: 'e024',
    iconset: 0,
    name: 'detail',
    new: false
  }, {
    code: 'e60b',
    iconset: 1,
    name: 'device',
    new: false
  }, {
    code: 'e61b',
    iconset: 1,
    name: 'device-an',
    new: false
  }, {
    code: 'e60c',
    iconset: 1,
    name: 'device-master',
    new: false
  }, {
    code: 'e61a',
    iconset: 1,
    name: 'device2',
    new: false
  }, {
    code: 'e025',
    iconset: 0,
    name: 'discover',
    new: false
  }, {
    code: 'e026',
    iconset: 0,
    name: 'domain',
    new: false
  }, {
    code: 'e027',
    iconset: 0,
    name: 'download',
    new: false
  }, {
    code: 'e0c4',
    iconset: 0,
    name: 'droplet',
    new: false
  }, {
    code: 'ed03',
    iconset: 2,
    name: 'edge',
    new: false
  }, {
    code: 'e028',
    iconset: 0,
    name: 'edit',
    new: false
  }, {
    code: 'e029',
    iconset: 0,
    name: 'email',
    new: false
  }, {
    code: 'e02a',
    iconset: 0,
    name: 'email-arrow-o',
    new: false
  }, {
    code: 'e502',
    iconset: 8,
    name: 'email-business-o',
    new: true
  }, {
    code: 'e02b',
    iconset: 0,
    name: 'email-o',
    new: false
  }, {
    code: 'ec00',
    iconset: 3,
    name: 'error',
    new: false
  }, {
    code: 'e916',
    iconset: 5,
    name: 'exchange',
    new: false
  }, {
    code: 'e02c',
    iconset: 0,
    name: 'export',
    new: false
  }, {
    code: 'e02d',
    iconset: 0,
    name: 'external-link',
    new: false
  }, {
    code: 'e095',
    iconset: 0,
    name: 'face-happy-o',
    new: false
  }, {
    code: 'e096',
    iconset: 0,
    name: 'face-neurtral-o',
    new: false
  }, {
    code: 'e097',
    iconset: 0,
    name: 'face-sad-o',
    new: false
  }, {
    code: 'e098',
    iconset: 0,
    name: 'face-smile-o',
    new: false
  }, {
    code: 'eb00',
    iconset: 7,
    name: 'file',
    new: false
  }, {
    code: 'eb01',
    iconset: 7,
    name: 'file-add-o',
    new: false
  }, {
    code: 'eb02',
    iconset: 7,
    name: 'file-arrow-o',
    new: false
  }, {
    code: 'eb10',
    iconset: 7,
    name: 'file-audio-o',
    new: false
  }, {
    code: 'eb03',
    iconset: 7,
    name: 'file-close-o',
    new: false
  }, {
    code: 'eb04',
    iconset: 7,
    name: 'file-code-o',
    new: false
  }, {
    code: 'eb05',
    iconset: 7,
    name: 'file-copy-o',
    new: false
  }, {
    code: 'eb06',
    iconset: 7,
    name: 'file-excel-o',
    new: false
  }, {
    code: 'eb07',
    iconset: 7,
    name: 'file-image-o',
    new: false
  }, {
    code: 'eb12',
    iconset: 7,
    name: 'file-lock-o',
    new: false
  }, {
    code: 'eb08',
    iconset: 7,
    name: 'file-o',
    new: false
  }, {
    code: 'eb09',
    iconset: 7,
    name: 'file-pdf-o',
    new: false
  }, {
    code: 'eb0f',
    iconset: 7,
    name: 'file-ppt-o',
    new: false
  }, {
    code: 'eb0a',
    iconset: 7,
    name: 'file-source-o',
    new: false
  }, {
    code: 'eb0b',
    iconset: 7,
    name: 'file-text',
    new: false
  }, {
    code: 'eb0c',
    iconset: 7,
    name: 'file-text-o',
    new: false
  }, {
    code: 'eb11',
    iconset: 7,
    name: 'file-video-o',
    new: false
  }, {
    code: 'eb0d',
    iconset: 7,
    name: 'file-word-o',
    new: false
  }, {
    code: 'eb0e',
    iconset: 7,
    name: 'file-zip-o',
    new: false
  }, {
    code: 'e02e',
    iconset: 0,
    name: 'filter',
    new: false
  }, {
    code: 'ed09',
    iconset: 2,
    name: 'firefox',
    new: false
  }, {
    code: 'e503',
    iconset: 8,
    name: 'firewall-o',
    new: true
  }, {
    code: 'e02f',
    iconset: 0,
    name: 'flag',
    new: false
  }, {
    code: 'e030',
    iconset: 0,
    name: 'flag-check',
    new: false
  }, {
    code: 'e031',
    iconset: 0,
    name: 'flag-more',
    new: false
  }, {
    code: 'e032',
    iconset: 0,
    name: 'flag-o',
    new: false
  }, {
    code: 'e033',
    iconset: 0,
    name: 'folder',
    new: false
  }, {
    code: 'e034',
    iconset: 0,
    name: 'folder-add',
    new: false
  }, {
    code: 'e035',
    iconset: 0,
    name: 'folder-add-o',
    new: false
  }, {
    code: 'e036',
    iconset: 0,
    name: 'folder-cloud',
    new: false
  }, {
    code: 'e037',
    iconset: 0,
    name: 'folder-o',
    new: false
  }, {
    code: 'e038',
    iconset: 0,
    name: 'folder-open',
    new: false
  }, {
    code: 'e039',
    iconset: 0,
    name: 'folder-open-o',
    new: false
  }, {
    code: 'ea06',
    iconset: 6,
    name: 'fontsize',
    new: false
  }, {
    code: 'e099',
    iconset: 0,
    name: 'fullscreen',
    new: false
  }, {
    code: 'e0bb',
    iconset: 0,
    name: 'fullscreen-exit',
    new: false
  }, {
    code: 'e0be',
    iconset: 0,
    name: 'gavel',
    new: false
  }, {
    code: 'e03a',
    iconset: 0,
    name: 'globe',
    new: false
  }, {
    code: 'e03b',
    iconset: 0,
    name: 'globe-warning',
    new: false
  }, {
    code: 'ed04',
    iconset: 2,
    name: 'google',
    new: false
  }, {
    code: 'e03c',
    iconset: 0,
    name: 'help',
    new: false
  }, {
    code: 'e03d',
    iconset: 0,
    name: 'help-o',
    new: false
  }, {
    code: 'ed05',
    iconset: 2,
    name: 'ie',
    new: false
  }, {
    code: 'e03e',
    iconset: 0,
    name: 'import',
    new: false
  }, {
    code: 'e09a',
    iconset: 0,
    name: 'inbox',
    new: false
  }, {
    code: 'e0c1',
    iconset: 0,
    name: 'inbox-upload',
    new: false
  }, {
    code: 'ea07',
    iconset: 6,
    name: 'indent',
    new: false
  }, {
    code: 'ec01',
    iconset: 3,
    name: 'info',
    new: false
  }, {
    code: 'e03f',
    iconset: 0,
    name: 'info-o',
    new: false
  }, {
    code: 'e0c0',
    iconset: 0,
    name: 'info-s',
    new: false
  }, {
    code: 'e09b',
    iconset: 0,
    name: 'install',
    new: false
  }, {
    code: 'e09c',
    iconset: 0,
    name: 'investigation',
    new: false
  }, {
    code: 'e0d4',
    iconset: 0,
    name: 'ioc',
    new: true
  }, {
    code: 'ea08',
    iconset: 6,
    name: 'italic',
    new: false
  }, {
    code: 'e040',
    iconset: 0,
    name: 'key',
    new: false
  }, {
    code: 'e041',
    iconset: 0,
    name: 'key-add-o',
    new: false
  }, {
    code: 'e042',
    iconset: 0,
    name: 'key-close-o',
    new: false
  }, {
    code: 'e043',
    iconset: 0,
    name: 'key-down-o',
    new: false
  }, {
    code: 'e044',
    iconset: 0,
    name: 'key-o',
    new: false
  }, {
    code: 'e0d1',
    iconset: 0,
    name: 'key-off',
    new: true
  }, {
    code: 'e045',
    iconset: 0,
    name: 'key-reset-o',
    new: false
  }, {
    code: 'e046',
    iconset: 0,
    name: 'key-up-o',
    new: false
  }, {
    code: 'e60d',
    iconset: 1,
    name: 'laptop',
    new: false
  }, {
    code: 'e60e',
    iconset: 1,
    name: 'laptop-group',
    new: false
  }, {
    code: 'e0bc',
    iconset: 0,
    name: 'lifebuoy',
    new: false
  }, {
    code: 'e0c5',
    iconset: 0,
    name: 'light',
    new: false
  }, {
    code: 'e0c6',
    iconset: 0,
    name: 'light-o',
    new: false
  }, {
    code: 'e0cd',
    iconset: 0,
    name: 'light2-o',
    new: false
  }, {
    code: 'ea11',
    iconset: 6,
    name: 'link',
    new: false
  }, {
    code: 'ea12',
    iconset: 6,
    name: 'link-break',
    new: false
  }, {
    code: 'ea14',
    iconset: 6,
    name: 'link-thin',
    new: false
  }, {
    code: 'ea09',
    iconset: 6,
    name: 'list-ol',
    new: false
  }, {
    code: 'ea0a',
    iconset: 6,
    name: 'list-ul',
    new: false
  }, {
    code: 'e047',
    iconset: 0,
    name: 'location',
    new: false
  }, {
    code: 'e048',
    iconset: 0,
    name: 'lock',
    new: false
  }, {
    code: 'e049',
    iconset: 0,
    name: 'lock-open',
    new: false
  }, {
    code: 'e04a',
    iconset: 0,
    name: 'log',
    new: false
  }, {
    code: 'ec02',
    iconset: 3,
    name: 'low',
    new: false
  }, {
    code: 'e504',
    iconset: 8,
    name: 'machine-learning-o',
    new: true
  }, {
    code: 'e09d',
    iconset: 0,
    name: 'magic',
    new: false
  }, {
    code: 'e505',
    iconset: 8,
    name: 'malware',
    new: true
  }, {
    code: 'e04b',
    iconset: 0,
    name: 'manage',
    new: false
  }, {
    code: 'e805',
    iconset: 4,
    name: 'map',
    new: false
  }, {
    code: 'e04c',
    iconset: 0,
    name: 'map-marker',
    new: false
  }, {
    code: 'e04d',
    iconset: 0,
    name: 'menu',
    new: false
  }, {
    code: 'e04e',
    iconset: 0,
    name: 'minus',
    new: false
  }, {
    code: 'e0ba',
    iconset: 0,
    name: 'minus-circle-o',
    new: false
  }, {
    code: 'e04f',
    iconset: 0,
    name: 'minus-square-o',
    new: false
  }, {
    code: 'e60f',
    iconset: 1,
    name: 'mobile',
    new: false
  }, {
    code: 'e610',
    iconset: 1,
    name: 'mobile-group',
    new: false
  }, {
    code: 'e620',
    iconset: 1,
    name: 'mobile-off',
    new: false
  }, {
    code: 'e050',
    iconset: 0,
    name: 'monitoring',
    new: false
  }, {
    code: 'e0c7',
    iconset: 0,
    name: 'moon',
    new: false
  }, {
    code: 'e051',
    iconset: 0,
    name: 'more',
    new: false
  }, {
    code: 'e052',
    iconset: 0,
    name: 'more-horiz',
    new: false
  }, {
    code: 'e09e',
    iconset: 0,
    name: 'move',
    new: false
  }, {
    code: 'e61d',
    iconset: 1,
    name: 'nas',
    new: false
  }, {
    code: 'e09f',
    iconset: 0,
    name: 'note-o',
    new: false
  }, {
    code: 'e053',
    iconset: 0,
    name: 'object-arrow-o',
    new: false
  }, {
    code: 'e054',
    iconset: 0,
    name: 'object-close-o',
    new: false
  }, {
    code: 'e055',
    iconset: 0,
    name: 'object-error-o',
    new: false
  }, {
    code: 'ed0a',
    iconset: 2,
    name: 'opera',
    new: false
  }, {
    code: 'ea0b',
    iconset: 6,
    name: 'outdent',
    new: false
  }, {
    code: 'e056',
    iconset: 0,
    name: 'partner-add-o',
    new: false
  }, {
    code: 'e057',
    iconset: 0,
    name: 'partner-close-o',
    new: false
  }, {
    code: 'e058',
    iconset: 0,
    name: 'partner-error-o',
    new: false
  }, {
    code: 'e059',
    iconset: 0,
    name: 'partner-o',
    new: false
  }, {
    code: 'ea0c',
    iconset: 6,
    name: 'paste',
    new: false
  }, {
    code: 'e0a0',
    iconset: 0,
    name: 'pause',
    new: false
  }, {
    code: 'e0a1',
    iconset: 0,
    name: 'picture',
    new: false
  }, {
    code: 'e0a2',
    iconset: 0,
    name: 'pin-star',
    new: false
  }, {
    code: 'e05a',
    iconset: 0,
    name: 'plan-add',
    new: false
  }, {
    code: 'e05b',
    iconset: 0,
    name: 'plan-pending',
    new: false
  }, {
    code: 'e05c',
    iconset: 0,
    name: 'plan-status',
    new: false
  }, {
    code: 'e0a3',
    iconset: 0,
    name: 'play',
    new: false
  }, {
    code: 'e05d',
    iconset: 0,
    name: 'print',
    new: false
  }, {
    code: 'e506',
    iconset: 8,
    name: 'ransomware-o',
    new: true
  }, {
    code: 'e0ce',
    iconset: 0,
    name: 'rca',
    new: false
  }, {
    code: 'ea0d',
    iconset: 6,
    name: 'redo',
    new: false
  }, {
    code: 'e05e',
    iconset: 0,
    name: 'refresh',
    new: false
  }, {
    code: 'e0d5',
    iconset: 0,
    name: 'registry',
    new: true
  }, {
    code: 'ea13',
    iconset: 6,
    name: 'rename',
    new: false
  }, {
    code: 'e0a4',
    iconset: 0,
    name: 'reorder',
    new: false
  }, {
    code: 'e0a5',
    iconset: 0,
    name: 'reply',
    new: false
  }, {
    code: 'e05f',
    iconset: 0,
    name: 'report',
    new: false
  }, {
    code: 'e0d3',
    iconset: 0,
    name: 'resize-horizontal',
    new: true
  }, {
    code: 'e0a7',
    iconset: 0,
    name: 'resize-nesw',
    new: false
  }, {
    code: 'e0a6',
    iconset: 0,
    name: 'resize-nwse',
    new: false
  }, {
    code: 'e0a8',
    iconset: 0,
    name: 'root-cause',
    new: false
  }, {
    code: 'e61e',
    iconset: 1,
    name: 'router',
    new: false
  }, {
    code: 'ed0b',
    iconset: 2,
    name: 'safari',
    new: false
  }, {
    code: 'e060',
    iconset: 0,
    name: 'save',
    new: false
  }, {
    code: 'e061',
    iconset: 0,
    name: 'save-o',
    new: false
  }, {
    code: 'e062',
    iconset: 0,
    name: 'scan-o',
    new: false
  }, {
    code: 'e063',
    iconset: 0,
    name: 'search-o',
    new: false
  }, {
    code: 'e611',
    iconset: 1,
    name: 'server',
    new: false
  }, {
    code: 'e612',
    iconset: 1,
    name: 'server-add',
    new: false
  }, {
    code: 'e613',
    iconset: 1,
    name: 'server-cloud',
    new: false
  }, {
    code: 'e614',
    iconset: 1,
    name: 'server-group',
    new: false
  }, {
    code: 'e615',
    iconset: 1,
    name: 'server-off',
    new: false
  }, {
    code: 'e616',
    iconset: 1,
    name: 'server-on',
    new: false
  }, {
    code: 'e617',
    iconset: 1,
    name: 'server-update',
    new: false
  }, {
    code: 'e618',
    iconset: 1,
    name: 'server-warning',
    new: false
  }, {
    code: 'e064',
    iconset: 0,
    name: 'settings',
    new: false
  }, {
    code: 'e065',
    iconset: 0,
    name: 'share',
    new: false
  }, {
    code: 'e066',
    iconset: 0,
    name: 'share-o',
    new: false
  }, {
    code: 'e0ca',
    iconset: 0,
    name: 'sherlock',
    new: false
  }, {
    code: 'e0a9',
    iconset: 0,
    name: 'shuffle',
    new: false
  }, {
    code: 'e0aa',
    iconset: 0,
    name: 'slider',
    new: false
  }, {
    code: 'e917',
    iconset: 5,
    name: 'sort-down',
    new: false
  }, {
    code: 'e918',
    iconset: 5,
    name: 'sort-up',
    new: false
  }, {
    code: 'e507',
    iconset: 8,
    name: 'spam-o',
    new: true
  }, {
    code: 'e067',
    iconset: 0,
    name: 'sphere',
    new: false
  }, {
    code: 'e068',
    iconset: 0,
    name: 'spinner',
    new: false
  }, {
    code: 'e508',
    iconset: 8,
    name: 'spyware',
    new: true
  }, {
    code: 'e069',
    iconset: 0,
    name: 'star',
    new: false
  }, {
    code: 'e06a',
    iconset: 0,
    name: 'star-half',
    new: false
  }, {
    code: 'e06b',
    iconset: 0,
    name: 'star-o',
    new: false
  }, {
    code: 'e0ab',
    iconset: 0,
    name: 'stop',
    new: false
  }, {
    code: 'ea0e',
    iconset: 6,
    name: 'strikethrough',
    new: false
  }, {
    code: 'ec03',
    iconset: 3,
    name: 'success',
    new: false
  }, {
    code: 'e0c8',
    iconset: 0,
    name: 'sun',
    new: false
  }, {
    code: 'e0c9',
    iconset: 0,
    name: 'sun-o',
    new: false
  }, {
    code: 'e06c',
    iconset: 0,
    name: 'sync',
    new: false
  }, {
    code: 'ed00',
    iconset: 2,
    name: 't-ball',
    new: false
  }, {
    code: 'e06d',
    iconset: 0,
    name: 'tag',
    new: false
  }, {
    code: 'e06e',
    iconset: 0,
    name: 'tag-add',
    new: false
  }, {
    code: 'e509',
    iconset: 8,
    name: 'target-o',
    new: true
  }, {
    code: 'e06f',
    iconset: 0,
    name: 'task',
    new: false
  }, {
    code: 'e070',
    iconset: 0,
    name: 'task-add-o',
    new: false
  }, {
    code: 'e071',
    iconset: 0,
    name: 'task-arrow-o',
    new: false
  }, {
    code: 'e072',
    iconset: 0,
    name: 'task-close-o',
    new: false
  }, {
    code: 'e073',
    iconset: 0,
    name: 'task-list-o',
    new: false
  }, {
    code: 'e074',
    iconset: 0,
    name: 'task-o',
    new: false
  }, {
    code: 'e0bf',
    iconset: 0,
    name: 'terminal',
    new: false
  }, {
    code: 'e0ac',
    iconset: 0,
    name: 'thumbtack',
    new: false
  }, {
    code: 'ee0bd',
    iconset: 0,
    name: 'time-off',
    new: false
  }, {
    code: 'e0cf',
    iconset: 0,
    name: 'treat-investigation',
    new: false
  }, {
    code: 'e094',
    iconset: 0,
    name: 'treeview',
    new: false
  }, {
    code: 'e0cc',
    iconset: 0,
    name: 'trend-link',
    new: false
  }, {
    code: 'e619',
    iconset: 1,
    name: 'TV',
    new: false
  }, {
    code: 'ec04',
    iconset: 3,
    name: 'unavailable',
    new: false
  }, {
    code: 'ea0f',
    iconset: 6,
    name: 'underline',
    new: false
  }, {
    code: 'ea10',
    iconset: 6,
    name: 'undo',
    new: false
  }, {
    code: 'ec05',
    iconset: 3,
    name: 'unknow',
    new: false
  }, {
    code: 'e075',
    iconset: 0,
    name: 'upload',
    new: false
  }, {
    code: 'e50a',
    iconset: 8,
    name: 'url',
    new: true
  }, {
    code: 'e076',
    iconset: 0,
    name: 'user',
    new: false
  }, {
    code: 'e077',
    iconset: 0,
    name: 'user-add',
    new: false
  }, {
    code: 'e078',
    iconset: 0,
    name: 'user-add-o',
    new: false
  }, {
    code: 'e0ad',
    iconset: 0,
    name: 'user-change',
    new: false
  }, {
    code: 'e079',
    iconset: 0,
    name: 'user-close',
    new: false
  }, {
    code: 'e07a',
    iconset: 0,
    name: 'user-close-o',
    new: false
  }, {
    code: 'e07b',
    iconset: 0,
    name: 'user-export-o',
    new: false
  }, {
    code: 'e07c',
    iconset: 0,
    name: 'user-group-close',
    new: false
  }, {
    code: 'e07d',
    iconset: 0,
    name: 'user-group-warning',
    new: false
  }, {
    code: 'e07e',
    iconset: 0,
    name: 'user-import-o',
    new: false
  }, {
    code: 'e07f',
    iconset: 0,
    name: 'user-o',
    new: false
  }, {
    code: 'e080',
    iconset: 0,
    name: 'user-team',
    new: false
  }, {
    code: 'e081',
    iconset: 0,
    name: 'user-unknow',
    new: false
  }, {
    code: 'e082',
    iconset: 0,
    name: 'view',
    new: false
  }, {
    code: 'e083',
    iconset: 0,
    name: 'view-off',
    new: false
  }, {
    code: 'e0b3',
    iconset: 0,
    name: 'virus',
    new: false
  }, {
    code: 'ed0c',
    iconset: 2,
    name: 'virustotal',
    new: false
  }, {
    code: 'ec06',
    iconset: 3,
    name: 'warning-circle',
    new: false
  }, {
    code: 'e084',
    iconset: 0,
    name: 'warning-triangle',
    new: false
  }, {
    code: 'e0b4',
    iconset: 0,
    name: 'widgets',
    new: false
  }, {
    code: 'e0b6',
    iconset: 0,
    name: 'wifi',
    new: false
  }, {
    code: 'e085',
    iconset: 0,
    name: 'window-list',
    new: false
  }, {
    code: 'ed06',
    iconset: 2,
    name: 'window8',
    new: false
  }, {
    code: 'e0d7',
    iconset: 0,
    name: 'winevent',
    new: true
  }, {
    code: 'e086',
    iconset: 0,
    name: 'wipe',
    new: false
  }, {
    code: 'e087',
    iconset: 0,
    name: 'wipe-close',
    new: false
  }, {
    code: 'e0d6',
    iconset: 0,
    name: 'wmi',
    new: true
  }, {
    code: 'e0d0',
    iconset: 0,
    name: 'yoda',
    new: false
  }, {
    code: 'e0b0',
    iconset: 0,
    name: 'zoom-in',
    new: false
  }, {
    code: 'e0b1',
    iconset: 0,
    name: 'zoom-out',
    new: false
  }]
};

export default iconList;
