const routes = [
  {
    title: 'Getting Started',
    icon: 'list-open',
    routes: [
      { title: 'Installation', path: 'installation' },
      { title: 'Usage', path: 'usage' },
      { title: 'Versions', path: 'versions' },
      { title: 'Contributing', path: 'contributing' },
    ],
  },
  {
    title: 'System',
    icon: 'gavel',
    routes: [
      { title: 'Color Mode', path: 'color-mode' },
      { title: 'Color Style', path: 'color-style' },
      { title: 'Borders', path: 'borders' },
      { title: 'Breakpoints', path: 'breakpoints' },
      { title: 'Colors', path: 'colors' },
      { title: 'Outlines', path: 'outlines' },
      { title: 'Positions', path: 'positions' },
      { title: 'Spacing', path: 'spacing' },
      { title: 'Sizes', path: 'sizes' },
      { title: 'Shadows', path: 'shadows' },
      { title: 'Typography', path: 'typography' },
    ],
  },
  {
    title: 'Components',
    icon: 'widgets',
    routes: [
      { title: 'DATA DISPLAY', heading: true },
      { title: 'Accordion', path: 'accordion' },
      { title: 'Badge', path: 'badge' },
      { title: 'Divider', path: 'divider' },
      { title: 'Modal', path: 'modal' },
      { title: 'Popover', path: 'popover' },
      { title: 'Table', path: 'table' },
      { title: 'Tag', path: 'tag' },
      { title: 'Tooltip', path: 'tooltip' },

      { title: 'FEEDBACK', heading: true },
      { title: 'Alert', path: 'alert' },
      { title: 'Skeleton', path: 'skeleton' },
      { title: 'Spinner', path: 'spinner' },
      { title: 'Toast', path: 'toast' },

      { title: 'FORMS', heading: true },
      { title: 'Button', path: 'button' },
      { title: 'ButtonBase', path: 'buttonbase' },
      { title: 'ButtonGroup', path: 'buttongroup' },
      { title: 'Checkbox', path: 'checkbox' },
      { title: 'CheckboxGroup', path: 'checkboxgroup' },
      { title: 'FlatButton', path: 'flatbutton' },
      { title: 'Input', path: 'input' },
      { title: 'InputBase', path: 'inputbase' },
      { title: 'InputGroup', path: 'inputgroup' },
      { title: 'LinkButton', path: 'linkbutton' },
      { title: 'Radio', path: 'radio' },
      { title: 'RadioGroup', path: 'radiogroup' },
      { title: 'SearchInput', path: 'searchinput' },
      { title: 'Select', path: 'select' },
      { title: 'Switch', path: 'switch' },
      { title: 'Textarea', path: 'textarea' },

      { title: 'LAYOUT', heading: true },
      { title: 'Box', path: 'box' },
      { title: 'ControlBox', path: 'controlbox' },
      { title: 'Flex', path: 'flex' },
      { title: 'Grid', path: 'grid' },
      { title: 'Space', path: 'space' },
      { title: 'Stack', path: 'stack' },

      { title: 'MEDIA AND ICONS', heading: true },
      { title: 'Icon', path: 'icon' },
      { title: 'Image', path: 'image' },
      { title: 'SVGIcon', path: 'svgicon' },

      { title: 'NAVIGATION', heading: true },
      { title: 'Drawer', path: 'drawer' },
      { title: 'Link', path: 'link' },
      { title: 'ButtonLink', path: 'buttonlink' }, // TODO: 404
      { title: 'Menu', path: 'menu' },
      { title: 'Pagination', path: 'pagination' },
      { title: 'Tabs', path: 'tabs' },

      { title: 'TYPOGRAPHY', heading: true },
      { title: 'Text', path: 'text' },
      { title: 'TextLabel', path: 'textlabel' },

      { title: 'UTILS', heading: true },
      { title: 'CSSBaseline', path: 'cssbaseline' },
      { title: 'Scrollbar', path: 'scrollbar' },
      { title: 'Transitions', path: 'transitions' },
    ],
  },
  {
    title: 'Hooks',
    icon: 'hook',
    routes: [
      { title: 'useConst', path: 'use-const' },
      { title: 'useEffectOnce', path: 'use-effect-once' },
      { title: 'useHydrated', path: 'use-hydrated' },
      { title: 'useLatest', path: 'use-latest' },
      { title: 'usePrevious', path: 'use-previous' },
      { title: 'useToggle', path: 'use-toggle' },
    ],
  },
];

export {
  routes,
};
