const routes = [
  {
    title: 'Getting Started',
    icon: 'list-open',
    path: 'getting-started',
    routes: [
      { title: 'Installation', path: 'getting-started/installation' },
      { title: 'Usage', path: 'getting-started/usage' },
      { title: 'Migration From v0.x to v1', path: 'getting-started/migration-v0x' },
      { title: 'Versions', path: 'getting-started/versions' },
      { title: 'Contributing', path: 'getting-started/contributing' },
    ],
  },
  {
    title: 'System',
    icon: 'gavel',
    path: 'system',
    routes: [
      { title: 'STYLED SYSTEM', heading: true },
      { title: 'Style Props', path: 'system/style-props' },
      { title: 'Pseudo Style Props', path: 'system/pseudo-style-props' },
      { title: 'Responsive Styles', path: 'system/responsive-styles' },

      { title: 'COLORS', heading: true },
      { title: 'Color Mode', path: 'system/color-mode' },
      { title: 'Color Style', path: 'system/color-style' },

      { title: 'THEME', heading: true },
      { title: 'Borders', path: 'system/borders' },
      { title: 'Breakpoints', path: 'system/breakpoints' },
      { title: 'Colors', path: 'system/colors' },
      { title: 'Fonts', path: 'system/fonts' },
      { title: 'Font Sizes', path: 'system/font-sizes' },
      { title: 'Font Weights', path: 'system/font-weights' },
      { title: 'Letter Spacings', path: 'system/letter-spacings' },
      { title: 'Line Heights', path: 'system/line-heights' },
      { title: 'Outlines', path: 'system/outlines' },
      { title: 'Radii', path: 'system/radii' },
      { title: 'Shadows', path: 'system/shadows' },
      { title: 'Sizes', path: 'system/sizes' },
      { title: 'Space', path: 'system/space' },
      { title: 'zIndices', path: 'system/z-indices' },
    ],
  },
  {
    title: 'Components',
    icon: 'widgets',
    path: 'components',
    routes: [
      { title: 'DATA DISPLAY', heading: true },
      { title: 'Accordion', path: 'components/accordion' },
      { title: 'Badge', path: 'components/badge' },
      { title: 'Divider', path: 'components/divider' },
      { title: 'Drawer', path: 'components/drawer' },
      { title: 'Modal', path: 'components/modal' },
      { title: 'Popover', path: 'components/popover' },
      { title: 'Table', path: 'components/table' },
      { title: 'Tag', path: 'components/tag' },
      { title: 'Tooltip', path: 'components/tooltip' },

      { title: 'FEEDBACK', heading: true },
      { title: 'Alert', path: 'components/alert' },
      { title: 'Skeleton', path: 'components/skeleton' },
      { title: 'Spinner', path: 'components/spinner' },
      { title: 'Toast', path: 'components/toast' },

      { title: 'FORMS', heading: true },
      { title: 'Button', path: 'components/button' },
      { title: 'ButtonBase', path: 'components/buttonbase' },
      { title: 'ButtonGroup', path: 'components/buttongroup' },
      { title: 'Checkbox', path: 'components/checkbox' },
      { title: 'CheckboxGroup', path: 'components/checkboxgroup' },
      { title: 'FlatButton', path: 'components/flatbutton' },
      { title: 'Input', path: 'components/input' },
      { title: 'InputBase', path: 'components/inputbase' },
      { title: 'InputGroup', path: 'components/inputgroup' },
      { title: 'LinkButton', path: 'components/linkbutton' },
      { title: 'Radio', path: 'components/radio' },
      { title: 'RadioGroup', path: 'components/radiogroup' },
      { title: 'SearchInput', path: 'components/searchinput' },
      { title: 'Select', path: 'components/select' },
      { title: 'Switch', path: 'components/switch' },
      { title: 'Textarea', path: 'components/textarea' },

      { title: 'LAYOUT', heading: true },
      { title: 'Box', path: 'components/box' },
      { title: 'ControlBox', path: 'components/controlbox' },
      { title: 'Flex', path: 'components/flex' },
      { title: 'Grid', path: 'components/grid' },
      { title: 'Space', path: 'components/space' },
      { title: 'Stack', path: 'components/stack' },

      { title: 'MEDIA AND ICONS', heading: true },
      { title: 'Icon', path: 'components/icon' },
      { title: 'Image', path: 'components/image' },
      { title: 'SVGIcon', path: 'components/svgicon' },

      { title: 'NAVIGATION', heading: true },
      { title: 'Link', path: 'components/link' },
      { title: 'ButtonLink 🚧', path: 'components/buttonlink' },
      { title: 'Menu', path: 'components/menu' },
      { title: 'Pagination', path: 'components/pagination' },
      //{ title: 'Tabs', path: 'components/tabs' }, // TODO

      { title: 'TRANSITIONS', heading: true },
      { title: 'Transitions', path: 'components/transitions' },
      { title: 'Transitions / Collapse', path: 'components/transitions/collapse' },
      { title: 'Transitions / Fade', path: 'components/transitions/fade' },
      { title: 'Transitions / Grow', path: 'components/transitions/grow' },
      { title: 'Transitions / Scale', path: 'components/transitions/scale' },
      { title: 'Transitions / Slide', path: 'components/transitions/slide' },
      { title: 'Transitions / Zoom', path: 'components/transitions/zoom' },

      { title: 'TYPOGRAPHY', heading: true },
      { title: 'Text', path: 'components/text' },
      { title: 'TextLabel', path: 'components/textlabel' },

      { title: 'UTILS', heading: true },
      { title: 'CSSBaseline', path: 'components/cssbaseline' },
      { title: 'Presence 🚧', path: 'components/presence' },
      { title: 'Scrollbar', path: 'components/scrollbar' },
      { title: 'VisuallyHidden 🚧', path: 'components/visually-hidden' },
    ],
  },
  {
    title: 'Hooks',
    icon: 'hook',
    path: 'hooks',
    routes: [
      { title: 'useConst', path: 'hooks/use-const' },
      { title: 'useEffectOnce', path: 'hooks/use-effect-once' },
      { title: 'useHydrated', path: 'hooks/use-hydrated' },
      { title: 'useIsomorphicEffect', path: 'hooks/use-isomorphic-effect' },
      { title: 'useLatest', path: 'hooks/use-latest' },
      { title: 'usePrevious', path: 'hooks/use-previous' },
      { title: 'useToggle', path: 'hooks/use-toggle' },
    ],
  },
];

export {
  routes,
};
