export const fruitItems = [
  { id: 'acerola', label: 'Acerola' },
  { id: 'ackee', label: 'Ackee' },
  { id: 'ambarella', label: 'Ambarella' },
  { id: 'apple', label: 'Apple' },
  { id: 'apricot', label: 'Apricot' },
  { id: 'avocado', label: 'Avocado' },
  { id: 'banana', label: 'Banana' },
  { id: 'bilberry', label: 'Bilberry' },
  { id: 'blackberry', label: 'Blackberry' },
  { id: 'blackcurrant', label: 'Blackcurrant' },
  { id: 'blood-orange', label: 'Blood orange' },
  { id: 'blueberry', label: 'Blueberry' },
  { id: 'boysenberry', label: 'Boysenberry' },
  { id: 'breadfruit', label: 'Breadfruit' },
  { id: 'buddha-hand', label: 'Buddha’s hand' },
  { id: 'cactus-pear', label: 'Cactus pear' },
  { id: 'calamansi', label: 'Calamansi' },
  { id: 'cantaloupe', label: 'Cantaloupe' },
  { id: 'cape-gooseberry', label: 'Cape gooseberry' },
  { id: 'cherimoya', label: 'Cherimoya' },
  { id: 'cherry', label: 'Cherry' },
  { id: 'chokeberry', label: 'Chokeberry' },
  { id: 'citron', label: 'Citron' },
  { id: 'clementine', label: 'Clementine' },
  { id: 'cloudberry', label: 'Cloudberry' },
  { id: 'coconut', label: 'Coconut' },
  { id: 'crabapple', label: 'Crabapple' },
  { id: 'cranberry', label: 'Cranberry' },
  { id: 'currant', label: 'Currant' },
  { id: 'custard-apple', label: 'Custard apple' },
  { id: 'damson', label: 'Damson' },
  { id: 'date', label: 'Date' },
  { id: 'dewberry', label: 'Dewberry' },
  { id: 'dragonfruit', label: 'Dragonfruit' },
  { id: 'durian', label: 'Durian' },
  { id: 'elderberry', label: 'Elderberry' },
  { id: 'feijoa', label: 'Feijoa' },
  { id: 'fig', label: 'Fig' },
  { id: 'goji-berry', label: 'Goji berry' },
  { id: 'gooseberry', label: 'Gooseberry' },
  { id: 'granadilla', label: 'Granadilla' },
  { id: 'grape', label: 'Grape' },
  { id: 'grapefruit', label: 'Grapefruit' },
  { id: 'greengage', label: 'Greengage' },
  { id: 'ground-cherry', label: 'Ground cherry' },
  { id: 'guava', label: 'Guava' },
  { id: 'hackberry', label: 'Hackberry' },
  { id: 'hawthorn', label: 'Hawthorn' },
  { id: 'honeydew', label: 'Honeydew' },
  { id: 'huckleberry', label: 'Huckleberry' },
  { id: 'imbe', label: 'Imbe' },
  { id: 'jabuticaba', label: 'Jabuticaba' },
  { id: 'jackfruit', label: 'Jackfruit' },
  { id: 'jambul', label: 'Jambul' },
  { id: 'jujube', label: 'Jujube' },
  { id: 'kaffir-lime', label: 'Kaffir lime' },
  { id: 'karonda', label: 'Karonda' },
  { id: 'kiwano', label: 'Kiwano' },
  { id: 'kiwi', label: 'Kiwi' },
  { id: 'kumquat', label: 'Kumquat' },
  { id: 'lemon', label: 'Lemon' },
  { id: 'lime', label: 'Lime' },
  { id: 'limeberry', label: 'Limeberry' },
  { id: 'lingonberry', label: 'Lingonberry' },
  { id: 'loganberry', label: 'Loganberry' },
  { id: 'longan', label: 'Longan' },
  { id: 'loquat', label: 'Loquat' },
  { id: 'lychee', label: 'Lychee' },
  { id: 'mandarin', label: 'Mandarin' },
  { id: 'mango', label: 'Mango' },
  { id: 'mangosteen', label: 'Mangosteen' },
  { id: 'marula', label: 'Marula' },
  { id: 'medlar', label: 'Medlar' },
  { id: 'melon', label: 'Melon' },
  { id: 'miracle-fruit', label: 'Miracle fruit' },
  { id: 'mountain-apple', label: 'Mountain apple' },
  { id: 'mulberry', label: 'Mulberry' },
  { id: 'nance', label: 'Nance' },
  { id: 'naranjilla', label: 'Naranjilla' },
  { id: 'nectarine', label: 'Nectarine' },
  { id: 'olive', label: 'Olive' },
  { id: 'orange', label: 'Orange' },
  { id: 'papaya', label: 'Papaya' },
  { id: 'passionfruit', label: 'Passionfruit' },
  { id: 'pawpaw', label: 'Pawpaw' },
  { id: 'peach', label: 'Peach' },
  { id: 'pear', label: 'Pear' },
  { id: 'pepino', label: 'Pepino' },
  { id: 'persimmon', label: 'Persimmon' },
  { id: 'physalis', label: 'Physalis' },
  { id: 'pineapple', label: 'Pineapple' },
  { id: 'pitanga', label: 'Pitanga' },
  { id: 'plantain', label: 'Plantain' },
  { id: 'plum', label: 'Plum' },
  { id: 'pomegranate', label: 'Pomegranate' },
  { id: 'pomelo', label: 'Pomelo' },
  { id: 'prickly-pear', label: 'Prickly pear' },
  { id: 'pulasan', label: 'Pulasan' },
  { id: 'quince', label: 'Quince' },
  { id: 'rambutan', label: 'Rambutan' },
  { id: 'raspberry', label: 'Raspberry' },
  { id: 'redcurrant', label: 'Redcurrant' },
  { id: 'rose-apple', label: 'Rose apple' },
  { id: 'rowan', label: 'Rowan' },
  { id: 'salak', label: 'Salak' },
  { id: 'salmonberry', label: 'Salmonberry' },
  { id: 'santol', label: 'Santol' },
  { id: 'sapodilla', label: 'Sapodilla' },
  { id: 'satsuma', label: 'Satsuma' },
  { id: 'sea-buckthorn', label: 'Sea buckthorn' },
  { id: 'serviceberry', label: 'Serviceberry' },
  { id: 'sloe', label: 'Sloe' },
  { id: 'soursop', label: 'Soursop' },
  { id: 'starfruit', label: 'Starfruit' },
  { id: 'strawberry', label: 'Strawberry' },
  { id: 'sugar-apple', label: 'Sugar apple' },
  { id: 'surinam-cherry', label: 'Surinam cherry' },
  { id: 'tamarind', label: 'Tamarind' },
  { id: 'tangerine', label: 'Tangerine' },
  { id: 'tayberry', label: 'Tayberry' },
  { id: 'thimbleberry', label: 'Thimbleberry' },
  { id: 'ugli-fruit', label: 'Ugli fruit' },
  { id: 'vanilla-fruit', label: 'Vanilla fruit' },
  { id: 'watermelon', label: 'Watermelon' },
  { id: 'white-currant', label: 'White currant' },
  { id: 'wineberry', label: 'Wineberry' },
  { id: 'wood-apple', label: 'Wood apple' },
  { id: 'youngberry', label: 'Youngberry' },
  { id: 'yuzu', label: 'Yuzu' },
  { id: 'ziziphus-fruit', label: 'Ziziphus fruit' },
];
