#!/bin/bash

sed "s|__TONIC_UI_MASTER_BRANCH_NAME__|${TONIC_UI_MASTER_BRANCH_NAME}|g; s|__TONIC_UI_MASTER_BRANCH_DOCUMENTATION__|${TONIC_UI_MASTER_BRANCH_DOCUMENTATION}|g; s|__TONIC_UI_MASTER_BRANCH_SOURCE_CODE__|${TONIC_UI_MASTER_BRANCH_SOURCE_CODE}|g; s|__TONIC_UI_V1_RELEASE_VERSION__|${TONIC_UI_V1_RELEASE_VERSION}|g; s|__TONIC_UI_V1_RELEASE_DOCUMENTATION__|${TONIC_UI_V1_RELEASE_DOCUMENTATION}|g; s|__TONIC_UI_V1_RELEASE_NOTES__|${TONIC_UI_V1_RELEASE_NOTES}|g; s|__TONIC_UI_V0_RELEASE_VERSION__|${TONIC_UI_V0_RELEASE_VERSION}|g; s|__TONIC_UI_V0_RELEASE_DOCUMENTATION__|${TONIC_UI_V0_RELEASE_DOCUMENTATION}|g; s|__TONIC_UI_V0_RELEASE_NOTES__|${TONIC_UI_V0_RELEASE_NOTES}|g;" \
  pages/versions.mdx.template > pages/versions.mdx
